### ISSUE TITLE
Missing fortios_system_config_backup_restore ?

### ISSUE THREAD

**Issue by kaon1** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#100]
Hi, 

Is there an equivalent module to fortios_system_config_backup_restore in this newest version? 

I see it in version 1.1.2 but not on the latest.

**Comment by JieX19** [comment]
Hi @kaon1,

We've got two powerful modules **fortios_monitor_fact** and **fortios_monitor** in our new release to do lots of tasks including backup and restore. Backup and restore are covered in the FAQ link https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/faq.html, please take a look and let me know if you have any questions.

**Comment by JieX19** [comment]
@kaon1,

version 2.0.0 is compatible with all FOS versions so you don't have to specify the Galaxy version to match the FOS installed on your device. Simply install it via command **ansible-galaxy collection install fortinet.fortios:2.0.0**

**Comment by kaon1** [comment]
This is perfect and what I was looking for. Thank you Jie
