### ISSUE TITLE
fortios_firewall_central_snat_map - Move policy

### ISSUE THREAD

**Issue by Superset1986** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#101]
Would it be possible to implement a move function like in fortios_firewall_policy ? 

In the situation where you have a "default" catch all NAT policy in your central nat table you need to move the newly created central nat policy manually since there is no option to move.

**Comment by chillancezen** [comment]
hi @JieX19,

looks like `central snat map` is movable, could you please help confirm it?
once confirmed, adding this module to https://github.com/fortinet-ansible-dev/fortios-ansible-generator/blob/devel/2.x/movable_modules.lst is supposed to be OK. 

thanks.
thanks @Superset1986 letting us know the issue.

**Comment by JieX19** [comment]
Hi @Superset1986 

Moving policy in fortios_firewall_central_snat_map is covered in the latest version, please install ansible-galaxy collection install fortinet.fortios:2.0.2 to use it.

Thanks!
