### ISSUE TITLE
duplicate of https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-sphinxdoc/issues/8

### ISSUE THREAD

**Issue by chillancezen** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#105]
**root cause**:   To upload PAC file, use the monitor API `/webproxy/pacfile/upload` and `pac_file_data` is not used in module `fortios_web_proxy_explicit`.

**fix plan**:  FOS galaxy `2.0.2`

**Comment by chillancezen** [comment]
https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-sphinxdoc/issues/8

**Comment by JieX19** [comment]
Hi,

Please install the latest version ansible-galaxy collection install fortinet.fortios:2.0.2 to use the module 'upload.webproxy.pacfile' in fortios_monitor and then run the task fortios_web_proxy_explicit.

When executing the task fortios_web_proxy_explicit, the first step would be uploading the pac file, it's not just a simple string as in CLI.

Please let me know if you have any other questions.

**Comment by JieX19** [comment]
Issue has fixed in 2.0.2
