### ISSUE TITLE
fortios_configuration_fact / fortios_facts get all policies

### ISSUE THREAD

**Issue by MalfuncEddie** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#106]
Hi,

Not sure if this is the right place to post this but I couldn't find any mailing lists.

I need to be able to report the policies of my fortigate to other people/ documentation. I would like to use this collection to dump the polcies facts to json.

The module fortios_configuration_fact has a selector "firewall_policy param: policyid type: int". But I need all policies. Is there a way to gather all facts or a way to list the id's.

Any help would be appreciated

**Comment by mbdraks** [comment]
The param is optional. Here's a working playbook that will dump all configure fw policies, tested with collection 2.0.2:

```
#!/usr/bin/env ansible-playbook
---
- hosts: Enterprise_Core

  tasks:
    - name: Get all firewall policies config
      fortinet.fortios.fortios_configuration_fact:
        access_token: "{{ fortios_access_token }}"
        selector: firewall_policy
      register: r

    - name: Set fw policy config list
      set_fact:
        fw_policy_config_list: "{{ r.meta.results }}"

    - name: Display fw policy list
      debug:
        var: fw_policy_config_list
```

**Comment by MalfuncEddie** [comment]
This is what I needed
