### ISSUE TITLE
Incremental router_prefix-list

### ISSUE THREAD

**Issue by gpipito** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#111]
Hi,

current router_prefix-list module  only reconfigure the entire prefix-list everytime, this requires some kind of rebuilding step to create the list from scratch.
It would be nice to have a simple way to push a single rule to an existing prefix-list.
In this case I would be allowed to create a new "rule", based on a template, to append to the desired prefix-list.

**Comment by JieX19** [comment]
Hi @gpipito,

This is a limitation compared with CLI. The rules in API design is not incrementally updated and we have to specify the whole rule set when creating/updating the router.prefix-list object. We've requested support from api team regarding this issue. 

I've marked this issue and will update you when the feature is available.

Thanks for your understanding.

**Comment by JieX19** [comment]
Hi @gpipito 

We implemented a feature to add new members to an existing entry by using the parameters 'member_state' and 'member_path', here's an example for your reference https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-use-the-member-operation-to-add-an-element-in-an-object.

I will close this issue and please reopen it or open a new issue if you still have any questions about this feature.

**Comment by JieX19** [comment]
Hi @gpipito 

We implemented a feature to add new members to an existing entry by using the parameters 'member_state' and 'member_path', here's an example for your reference https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-use-the-member-operation-to-add-an-element-in-an-object.

I will close this issue and please reopen it or open a new issue if you still have any questions about this feature.
