### ISSUE TITLE
Managing FortiGates using a jump host

### ISSUE THREAD

**Issue by br0v** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#116]
Dear all,

My apologies if this is not the correct place for issues like this. In my current project I need to connect to FortiGates using a jump host. I know it's possible in Ansible to use ProxyCommand for SSH connections, as described here: https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-configure-a-jump-host-to-access-servers-that-i-have-no-direct-access-to 
However, I know the FortiOS collection uses the RestAPI, not SSH.

Is there a way to use the FortiOS collection in a similar way?

**Comment by chillancezen** [comment]
@br0v , 

is it possible to run ansible in the jump host?

Ansible  needs direct network connectivity, it also works if you make a NAT in jump host which translates a port to FGT device.

**Comment by br0v** [comment]
@chillancezen ,

Thank you very much for your reply. The jump host is not currently running Ansible, we just use it to gain access to the internal network. We don't want two seperate instances of Ansible, we want everything managed from one location. 

I've managed to get the connection working using NAT on the jump host. This will require a NAT rule for each of the devices in the internal network, which is doable, but not perfect.

If you have a better solution (e.g. benefits of installing Ansible on the jump host), please let me know. If not, thanks again and feel free the close this issue.
