### ISSUE TITLE
fortios_monitor_fact error using selector system_firmware_upgrade_paths

### ISSUE THREAD

**Issue by br0v** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#123]
Dear all,

When using "system_firmware_upgrade_paths" as a param for the selector in the module "fortios_monitor_fact" I keep getting errors instead of actual results. 

Please see this simple playbook task below:

```yaml
  - name: Gather upgrade paths information
    fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: 'system_firmware_upgrade-paths'
```

Running the playbook results in the error below:

```json
fatal: [FGT-VM05]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": null,
            "params": null,
            "selector": "system_firmware_upgrade-paths",
            "vdom": "root"
        }
    },
    "meta": {
        "action": "upgrade-paths",
        "build": 419,
        "http_method": "GET",
        "http_status": 500,
        "name": "firmware",
        "path": "system",
        "serial": "HIDDENFORTHISCOMMENT",
        "status": "error",
        "vdom": "root",
        "version": "v6.0.12"
    },
    "msg": "Error in repo"
```

All other selector params I've tried so far seem to work. I've gotten this error on FortiOS version 6.0.12 (using a FortiGate 30E, 50E en VM) and 6.2.9 (using a FortiGate 60F). As far as I can see on the docs (https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_monitor_fact.html), I'm using this module in the correct way. 

I also wasn't certain which output I should expect since we are just experimenting with this module, I'd like to solve this issue so we can see if it is usable in our current setup.

Thanks in advance for your time.

**Comment by JieX19** [comment]
Hi @br0v 

I tried the module and it works. This module is supported on Fortios 6.0.12. 

Results got from the task.
```ok: [fortigate01] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": null,
            "filters": null,
            "formatters": null,
            "params": null,
            "selector": "system_firmware_upgrade-paths",
            "sorters": null,
            "vdom": "root"
        }
    },
    "meta": {
        "action": "upgrade-paths",
        "build": 1879,
        "http_method": "GET",
        "name": "firmware",
        "path": "system",
        "results": [
            {
                "from": {
                    "build": 1879,
                    "major": 6,
                    "minor": 4,
                    "patch": 6
                },
                "to": {
                    "build": 66,
                    "major": 7,
                    "minor": 0,
                    "patch": 0
                }
            }
```

Can you please try -vvvv when running the playbook, which can give more info about the error.

Also, please use the debugging command below on your device to see which step is failed. 

Debugging
Verbose output can help with debugging. To enable verbose debugging, use the following commands in the FortiGate CLI:

diagnose debug enable
diagnose debug application httpsd -1

**Comment by JieX19** [comment]
Feel free to open an issue if you still have any questions on this module.

Thanks!
