### ISSUE TITLE
Can Ansible handle 2FA with Fortitoken when using httpapi

### ISSUE THREAD

**Issue by hosseinoliabak** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#128]
I use FortiToken as 2nd factor authentication to login to a FortiGate. I would want to know if this is possible to pass the OTP when running the ansible-playbook command.

I have also prompted the user to enter the token (https://docs.ansible.com/ansible/latest/user_guide/playbooks_prompts.html#interactive-input-prompts)

but still getting:

```
ansible.module_utils.connection.ConnectionError: Wrong credentials. Please check\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by chillancezen** [comment]
2fa is not considered, we will update you later, thanks for your issue.

**Comment by JieX19** [comment]
Hi @hosseinoliabak 

We've had a discussion on this feature and tested on the api, it shows the result of fortios_access_token has higher priority, which means 2FA will be ignored if you use fortios_access_token even though 2FA is enabled on the device.

The fact is 2FA is useful when you're logging in with username and password. We recommend to use fortios_access_token, it's a safe way to access to the device. 

BTW, we will implement the feature for sure.

**Comment by hosseinoliabak** [comment]
Hi @JieX19,
Thanks for the comment.
I prefer waiting for the feature.
--
Thank you,
