### ISSUE TITLE
fortios_monitor - Clear soft in and soft out error in repo

### ISSUE THREAD

**Issue by apellini** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#130]
Hi,
I have written the following task:

`- name:  Execute clear soft in to receive the new network
    fortios_monitor:
      vdom: root
      selector: "clear-soft-in.router.bgp"`

But after launch I receive:

`failed: [fortigate] (item=root) => changed=false 
  ansible_loop_var: item
  item: root
  meta:
    action: clear-soft-in
    build: 6828
    http_status: 404
    name: bgp
    path: router
    serial: Serial
    status: error
    version: v6.0.10
  msg: Error in repo`

Seems that it doesn't find the API.

Regards,

Aldo Pellini

**Comment by JieX19** [comment]
Hi @apellini 

I am looking into the case and will get back to you ASAP.

Thanks.

**Comment by JieX19** [comment]
Hi @apellini 

I found it's a bug in the fortios rest-api. Can you please upgrade your device to fortios v7.0.0 or later to make sure the module works as expected. 

Feel free to open an issue if you have any other questions.

Thanks!
