### ISSUE TITLE
Monitor fact with selector "license_status " doesn't return list

### ISSUE THREAD

**Issue by JelleStu** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#145]
Hi,

I'm trying to loop through results from the license status selector with the fortios_monitor_fact.

But whenever I put the results in the loop I will receive an error: `"Invalid data passed to 'loop', it requires a list, got this instead:`

Playbook:
```
- hosts: fortigates
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Get license shizzle
    fortios_monitor_fact:
      vdom: "{{ vdom }}"
      access_token: "{{ access_token}} "
      selector: license_status 
    register: license

  - name: test loop
    debug:
      msg: "{{ item.key }} license is {{ item.status }}"
    with_items: "{{ license.meta.results }}" 
```

**Comment by JieX19** [comment]
Hi @JelleStu 

The meta results getting from the task is a **dict** and not a list, you can double check from the results of the first task 'Get license shizzle'.

So **with_dict** is the best way to iterate a dict obj, and also you can not get the item.status directly, 'cause status is just an attribute of the item.values, which means you need to get the item.values first and then get the attribute 'status' from the returned values by using the the built-in function 'get()'. 

**Here's the playbook I used:**

```
- hosts: fortigates
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Get license shizzle
    fortios_monitor_fact:
      vdom: "{{ vdom }}"
      access_token: "{{ access_token}}"
      selector: license_status
    register: license

  - name: test loop
    debug:
      msg: "{{ item.key }} license is {{ item.value.get('status') }} "
    with_dict: "{{ license.meta.results}}"
```

**Comment by JelleStu** [comment]
Thanks, did not knew this was an option in Ansible! :)
