### ISSUE TITLE
Documentation issue: application_list.entries.popularity expects a list of strings

### ISSUE THREAD

**Issue by jantari** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#146]
Hi,

I stumbled upon a mistake in the documentation for this module today.
At: https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_application_list.html
it says that:

> popularity - Application popularity filter (1 - 5, from least to most popular). `type: list` `choices: 1, 2, 3, 4, 5`

which implies I have to supply a list of integers (since there are no quotes around the numbers shown in "choices" and unquoted numbers in YAML/ansible are integers).

Then in the examples below ( https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_application_list.html#examples ) it shows:

> popularity: "1"

implying a single `string` value needs to be supplied, not a `list` since there are no `[ ]` brackets to create a list.

However BOTH documented ways to set the popularity are wrong and result in AssertionError.

I checked FNDN and it says `popularity` is a single string ( https://fndn.fortinet.net/index.php?/fortiapi/1-fortios/974/1/application/ ) like in the example below the ansible module documentation.

The way I actually had to do it for it to work and the AssertionError to go away was:

> popularity: ['1', '2', '3', '4', '5']

So a `list` of `strings`.

I think the documentation should be corrected to say: `type: list choices: '1', '2', '3', '4', '5'` and the example below the documentation should be `popularity: ["1"]`.

**Comment by JieX19** [comment]
Hi @jantari,

Thanks for raising this issue. There's a gap between our internal schema representation and open API. We will find a solution to solve such issues. 

Thank you again for your understanding.
