### ISSUE TITLE
Feature missing: extender-controller profile

### ISSUE THREAD

**Issue by winromulus** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#153]
Hi,

Any chance we might get a module for extender-controller to support extender profiles? I can't find any way yet to configure a profile or assign the extender to a profile

**Comment by JieX19** [comment]
Hi @winromulus 

Can you give me an example of your question? It helps us understand and evaluate the feature easily.

Thanks,
Jie

**Comment by winromulus** [comment]
@JieX19 - at least in FortiOS 7.x we have the ability to create fortiextender profiles and assign extenders to those profiles. I can't find anything to support this from Ansible.

**Comment by JieX19** [comment]
@winromulus 

Thanks for the feedback! In the monitor APIs, there're a few modules related to fortiextender, for example, 'reset.extender-controller.extender', which is used to reset a specific FortiExtender unit. 

The backend does not expose other APIs related to fortiextender, so ansible cannot support them at this moment.

Thanks for your understanding. We will definitely support more and more features in the future.

**Comment by JieX19** [comment]
Hi @winromulus,

I will close this issue as it's been a while and no further updates or responses have been received, indicating that the matter has likely been resolved or is no longer active.

Feel free to reopen it or open a new issue if you still have any questions.
