### ISSUE TITLE
Getting issue while running any fortios module

### ISSUE THREAD

**Issue by sajaltiwarine** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#156]
Hello,
I am getting below error while running any playbook with any fortios module, I am moving my existing playbook with old modules to the new one.

TASK [Gathering Facts] *********************************************************
fatal: [X.x.X.x]: FAILED! => {"msg": "network os fortinet.fortios.fortios is not supported"}

ansible --version
`[XX]# ansible --version
/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
ansible 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/napalm_ansible/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
`

Can someone help with what could be the issue?

playbook:

`- hosts: fortigate
  connection: httpapi
  collections:
  - community.fortios.fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: fortios_system_snmp_community
    fortios_system_snmp_community:
      vdom: root
      state: present
      system_snmp_community:
        events: cpu-high
        id: 1
        name: fdsie
        query_v1_port: 161
        query_v1_status: enable
        query_v2c_port: 161
        query_v2c_status: enable
        status: enable
        trap_v1_lport: 162
        trap_v1_rport: 162
        trap_v1_status: enable
        trap_v2c_lport: 162
        trap_v2c_rport: 162
        trap_v2c_status: enable`

Thank you in advance.

**Comment by JieX19** [comment]
Hi @sajaltiwarine 

It seems the error is caused by the inventory configuration. Here's the link that we use to help our users write a playbook.
https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/install.html
https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/playbook.html

Prepare host inventory
in our case we create a file named hosts:
```
[fortigates]
fortigate01 ansible_host=192.168.190.130 ansible_user="admin" ansible_password="password"
fortigate02 ansible_host=192.168.190.131 ansible_user="admin" ansible_password="password"
fortigate03 ansible_host=192.168.190.132 fortios_access_token=<your access token>

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
```

Also, you can upgrade the python to python3. The current collection is heavily relying on python 3.

**Comment by JieX19** [comment]
Hi @sajaltiwarine 

We're sending you this message to confirm this issue has been resolved. If you need any other support, feel free to open an issue.
