### ISSUE TITLE
fortios_user_group deletes the whole group. 

### ISSUE THREAD

**Issue by kar0v** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#161]
Hello, 
I'm trying to create a certain user and add that user to a few groups, however what the fortios_user_group does is it deletes the whole group and creates it again, then adds only that one user. 

This was done on FortiGate100E Firmware v6.4.7 build 1911(GA) 

`---
- collections:
  - fortinet.fortios
  connection: httpapi
  hosts: firewalls
  vars:
    ansible_httpapi_port: 4443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortios.fortios
    vdom: root
    user_name: ansible_automation_test
    user_group_names:
      - SSL VPN Users
      - vpn-sslvpn-access
  vars_files:
    - credentials.yml
  tasks:
  - name: Add an LDAP user via fortios_user_local
    fortios_user_local:
      vdom: root
      state: present
      user_local:
        auth_concurrent_override: disable
        ldap_server: JumpCloud
        name: "{{ user_name }}"
        status: enable
        two_factor: disable
        type: ldap
        username_case_sensitivity: enable
  - name: Add user to groups fortios_user_group
    fortios_user_group:
      vdom: root
      state: present
      user_group:
        member:
        - name: "{{ user_name }}"
        name: "{{ item }}"
    loop: "{{ user_group_names }}"
`

**Comment by JieX19** [comment]
Hi @kar0v 

FortiOS modules have a functionality called member_operation, which allows to add or delete a member from a list.

https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_user_group.html
https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_user_group.html

Using member_path and member_state (present/absent) to do the task.

**Comment by kar0v** [comment]
There is no mention on how to use member_path & member state in the documentation. When I tried to use member_state it was required to use member_path as well. I was unable to locate any examples for member_path & member_state as well. Where can I see more information about the member_path option?

**Comment by Raimond56** [comment]
Hey,
Use this documentation: https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.1.3/gen/fortios_user_group.html 
It shows member paths where it can be used.

**Comment by JieX19** [comment]
Hi @kar0v 

Here's an example of adding a user 'localuser1' to a group 'foogrp'.

```
tasks:
  - name: Add a user to a group
    fortios_user_group:
      vdom: "{{ vdom }}"
      state: present
      member_state: present
      member_path: member:name
      user_group:
        member:
          - name: userlocal1
        name: foogrp
```
Before executing the task, there's only one memeber 'guest' in this group.

This is the result after executing the task:
<img width="618" alt="result" src="https://user-images.githubusercontent.com/59745792/157127521-428c47fc-8158-444a-aa26-c9d4eadb1bc9.PNG">

Let me know if you have any questions.

**Comment by JieX19** [comment]
Hi, @kar0v I'm closing this issue due to lack of response. Feel free to open an issue if there're any issues.

**Comment by britel-chaimaa20** [comment]
Thanks @JieX19 for the `member_path` clarification. That works perfectly!!
