### ISSUE TITLE
add vdom on fortios get error

### ISSUE THREAD

**Issue by trump4coin** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#166]
Hi,

when using the following playbook 
`
- hosts: fortigate01
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Configure virtual domain.
    fortios_system_vdom:
      vdom:  "{{ vdom }}"
      state: "present"
      access_token: "1234"
      system_vdom:
        flag: "3"
        name: "default_name_4"
        short_name: "test"
        temporary: "6"
        vcluster_id: "7"
`

After execution i got 
`<1.1.1.1> EXEC /bin/sh -c 'rm -f -r /home/toto/.ansible/tmp/ansible-local-29610mn62m3y1/ansible-tmp-1645523772.3564107-29614-23316367008107/ > /dev/null 2>&1 && sleep 0'
fatal: [fortigate01]: FAILED! => {
    "msg": "module (ansible.legacy.setup) is missing interpreter line"
`
My env is: 
ansible [core 2.12.2]
  config file = /home/toto/40gate/ansible/playbook/ansible.cfg
  configured module search path = ['/home/toto/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/toto/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /home/toto/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/toto/ansible/bin/ansible
  python version = 3.9.1 (default, Feb  1 2022, 11:28:23) [GCC 8.3.0]
  jinja version = 3.0.3
  libyaml = True

Where is the error ???

**Comment by trump4coin** [comment]
> Hi,
> 
> when using the following playbook `
> 
>     * hosts: fortigate01
>       collections:
>       
>       * fortinet.fortios
>         connection: httpapi
>         vars:
>         vdom: "root"
>         ansible_httpapi_use_ssl: yes
>         ansible_httpapi_validate_certs: no
>         ansible_httpapi_port: 443
>         tasks:
>       * name: Configure virtual domain.
>         fortios_system_vdom:
>         vdom:  "{{ vdom }}"
>         state: "present"
>         access_token: "1234"
>         system_vdom:
>         flag: "3"
>         name: "default_name_4"
>         short_name: "test"
>         temporary: "6"
>         vcluster_id: "7"
>         `
> 
> 
> After execution i got `<1.1.1.1> EXEC /bin/sh -c 'rm -f -r /home/toto/.ansible/tmp/ansible-local-29610mn62m3y1/ansible-tmp-1645523772.3564107-29614-23316367008107/ > /dev/null 2>&1 && sleep 0' fatal: [fortigate01]: FAILED! => { "msg": "module (ansible.legacy.setup) is missing interpreter line" ` My env is: ansible [core 2.12.2] config file = /home/toto/40gate/ansible/playbook/ansible.cfg configured module search path = ['/home/toto/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules'] ansible python module location = /home/toto/ansible/lib/python3.9/site-packages/ansible ansible collection location = /home/toto/.ansible/collections:/usr/share/ansible/collections executable location = /home/toto/ansible/bin/ansible python version = 3.9.1 (default, Feb 1 2022, 11:28:23) [GCC 8.3.0] jinja version = 3.0.3 libyaml = True
> 
> Where is the error ???

gather_facts=no solve the issue ... but version 6.2.x or 6.4.x seems not supported

*
[WARNING]: Ansible has detected version mismatch between FortOS system and your playbook, see more details by specifying option -vvv
fatal: [fortigate01]: FAILED! => {"changed": false, "meta": {"build": 7197, "error": -553, "http_method": "POST", "http_status": 500, "name": "vdom", "path": "system", "revision": "bebc2938d5083a74cb988e6b8781e425", "revision_changed": false, "serial": "FG180FTKxxxxxxx", "status": "error", "vdom": "root", "version": "v6.2.9"}, "msg": "Error in repo", "version_check_warning": {"matched": false, "mismatches": ["option temporary(6) not supported since v6.0.11"], "system_version": "v6.2.9"}}

**Comment by trump4coin** [comment]
ansible-galaxy collection install fortinet.fortios:1.1.6 , i got another error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: Could not connect to https://1.1.1.1:443/logincheck: Tunnel connection failed: 403 Forbidden
fatal: [fortigate01]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/toto/.ansible/tmp/ansible-local-29954b89rkx2y/ansible-tmp-1645525749.773902-29959-157590193349526/AnsiballZ_fortios_system_vdom.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/toto/.ansible/tmp/ansible-local-29954b89rkx2y/ansible-tmp-1645525749.773902-29959-157590193349526/AnsiballZ_fortios_system_vdom.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/toto/.ansible/tmp/ansible-local-29954b89rkx2y/ansible-tmp-1645525749.773902-29959-157590193349526/AnsiballZ_fortios_system_vdom.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_vdom', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_vdom', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_system_vdom_payload_py_yqr6p/ansible_fortios_system_vdom_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_vdom.py\", line 321, in <module>\n  File \"/tmp/ansible_fortios_system_vdom_payload_py_yqr6p/ansible_fortios_system_vdom_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_vdom.py\", line 300, in main\n  File \"/tmp/ansible_fortios_system_vdom_payload_py_yqr6p/ansible_fortios_system_vdom_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_vdom.py\", line 257, in fortios_system\n  File \"/tmp/ansible_fortios_system_vdom_payload_py_yqr6p/ansible_fortios_system_vdom_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_vdom.py\", line 235, in system_vdom\n  File \"/tmp/ansible_fortios_system_vdom_payload_py_yqr6p/ansible_fortios_system_vdom_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 173, in set\n  File \"/tmp/ansible_fortios_system_vdom_payload_py_yqr6p/ansible_fortios_system_vdom_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Could not connect to https://1.1.1.1:443/logincheck: Tunnel connection failed: 403 Forbidden\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by JieX19** [comment]
Hi @trump4coin 

May I know what FOS version you're using? I also noticed that you used fortiOS collection 1.1.6, can you please upgrade to the latest version 2.1.4, which has more features and covers many bug fixes. Try this module after installing the new version.

Using command **ansible-galaxy collection install fortinet.fortios:2.1.4** to install the latest version.

I tried the above playbook on my side and everything works well.

**Comment by JieX19** [comment]
@trump4coin I'm closing this issue due to lack of response. Feel free to open an issue if there're any issues.

**Comment by miguelebf** [comment]
Hi, i have the same issue, with diagnose in cli of fortigate view this commands 
- config global
-  config system vdom
- edit "name_vdom"
- end
and should be only :
- config vdom
- edit "name_vdom"
- end
