### ISSUE TITLE
Spelling error in fortios.py 

### ISSUE THREAD

**Issue by gduross** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#168]
Hi Fortinet Ansible Dev Team,
Found a couple spelling errors in:

/ansible-galaxy-fortios-collection/blob/bfdcb660edb9701895c93a3e4a0458f38956507e/plugins/module_utils/fortios/fortios.py

results['mismatches'].append('option [%s]\' playload is inconsitent with schmea.' % (__concat_attribute_sequence(trace)))

Notice: inconsitent (should be inconsistent) and schmea (should be schema),

Thank you,
Gil

**Comment by JieX19** [comment]
Thank you! @gduross, we will fix the errors right away. They should be corrected in the next release.
