### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by Bergeron-755** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#171]
We could really benefits from adding "DIAG" feature/module for all collections (FAZ, FMG, Fortios, etc)

**Comment by JieX19** [comment]
Can you describe your workflow for using 'DIAG'? We don't currently have an exposed API from the backend for 'DIAG' info.

**Comment by JieX19** [comment]
Hi,

I will close this issue as it's been a while and no further updates or responses have been received, indicating that the matter has likely been resolved or is no longer active.

Feel free to reopen it or open a new issue if you have any questions.
