### ISSUE TITLE
Malformed Documentation of fortios_system_csf

### ISSUE THREAD

**Issue by simonai1254** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#176]
Hi

I was browsing through the module documentation and gotan error when reading the ansible docs about the Fortinet FortiOS FortiOS_System_CSF module ([reference])(https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_system_csf_module.html):

---

The documentation for the module plugin, fortinet.fortios.fortios_system_csf, was malformed.
The errors were:

```
1 validation error for ModuleDocSchema
doc -> options -> system_csf -> suboptions -> fabric_device -> suboptions -> access_token -> type
  string does not match regex "^(bits|bool|bytes|dict|float|int|json|jsonarg|list|path|raw|sid|str|tmppath|pathspec|pathlist)$" (type=value_error.str.regex; pattern=^(bits|bool|bytes|dict|float|int|json|jsonarg|list|path|raw|sid|str|tmppath|pathspec|pathlist)$)
````
---

Thanks :)

**Comment by JieX19** [comment]
Hi @simonai1254 

Thank you for finding the issue! It looks like something is wrong while rendering the doc page on the Ansible end. I will report it to Ansible. 

You can also check all the docs from https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.1.4/index.html. This is the doc page maintained by our team.

**Comment by JieX19** [comment]
Hi @simonai1254 

The doc shows normally now https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_system_csf_module.html

I will close the issue at this moment, marking it as resolved or completed. If you have any further questions or concerns, please feel free to reopen the ticket or create a new one.
