### ISSUE TITLE
Sanity tests failing in fortinet.fortios

### ISSUE THREAD

**Issue by dmsimard** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#181]
Greetings from the Ansible community working group,

The fortinet.fortios collection is included in the Ansible community package (``ansible`` on PyPI) and as such is expected to have CI which passes sanity tests (amongst other things) as per documented here: https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#ci-testing

We recently noticed that sanity tests were not running on a regular basis and [proposed a PR to enable them](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/pull/179), though development of the collection does not appear to happen on GitHub at first glance.

When running ``ansible-test sanity --docker`` on the latest version of the collection (2.1.5), there are multiple syntax errors that must be resolved -- for example:
```
Running sanity test "compile" on Python 3.9
ERROR: Found 3 compile issue(s) on python 3.9 which need to be resolved:
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_advice_of_charge.py:281:20: SyntaxError: filtered_data =
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_osu_provider_nai.py:238:20: SyntaxError: filtered_data =
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_terms_and_conditions.py:236:20: SyntaxError: filtered_data =
See documentation for help: https://docs.ansible.com/ansible-core/2.12/dev_guide/testing/sanity/compile.html
Running sanity test "compile" on Python 3.10
ERROR: Found 3 compile issue(s) on python 3.10 which need to be resolved:
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_advice_of_charge.py:281:20: SyntaxError: filtered_data =
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_osu_provider_nai.py:238:20: SyntaxError: filtered_data =
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_terms_and_conditions.py:236:20: SyntaxError: filtered_data =
See documentation for help: https://docs.ansible.com/ansible-core/2.12/dev_guide/testing/sanity/compile.html
Running sanity test "empty-init"
Running sanity test "future-import-boilerplate"
Running sanity test "ignores"
Running sanity test "import" on Python 2.7
ERROR: Found 8 import issue(s) on python 2.7 which need to be resolved:
ERROR: plugins/module_utils/fortios/facts/facts.py:27:0: traceback: ImportError: No module named network.common.facts.facts
ERROR: plugins/modules/fortios_configuration_fact.py:5181:22: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_export_config_playbook.py:5349:22: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_log_fact.py:5202:22: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_monitor_fact.py:4116:22: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_advice_of_charge.py:281:20: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_osu_provider_nai.py:238:20: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_terms_and_conditions.py:236:20: traceback: SyntaxError: invalid syntax
See documentation for help: https://docs.ansible.com/ansible-core/2.12/dev_guide/testing/sanity/import.html
Running sanity test "import" on Python 3.5
ERROR: Found 5 import issue(s) on python 3.5 which need to be resolved:
ERROR: plugins/module_utils/fortios/facts/facts.py:27:0: traceback: ImportError: No module named 'ansible.module_utils.network'
ERROR: plugins/modules/fortios_export_config_playbook.py:3811:0: traceback: ImportError: No module named 'yaml'
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_advice_of_charge.py:281:20: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_osu_provider_nai.py:238:20: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_terms_and_conditions.py:236:20: traceback: SyntaxError: invalid syntax
See documentation for help: https://docs.ansible.com/ansible-core/2.12/dev_guide/testing/sanity/import.html
Running sanity test "import" on Python 3.6
ERROR: Found 5 import issue(s) on python 3.6 which need to be resolved:
ERROR: plugins/module_utils/fortios/facts/facts.py:27:0: traceback: ModuleNotFoundError: No module named 'ansible.module_utils.network'
ERROR: plugins/modules/fortios_export_config_playbook.py:3811:0: traceback: ModuleNotFoundError: No module named 'yaml'
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_advice_of_charge.py:281:20: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_osu_provider_nai.py:238:20: traceback: SyntaxError: invalid syntax
ERROR: plugins/modules/fortios_wireless_controller_hotspot20_h2qp_terms_and_conditions.py:236:20: traceback: SyntaxError: invalid syntax
See documentation for help: https://docs.ansible.com/ansible-core/2.12/dev_guide/testing/sanity/import.html
```

If the collection is not improved to meet the [collection inclusion specifications](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst) in the near future, it may also be at risk of being removed from the community package.

Please acknowledge the issue and keep us updated. Thank you.

**Comment by dmsimard** [comment]
I've intended to create this issue for fortinet.fortimanager and mistakenly confused this repository with https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection instead so I've created another issue here: https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/issues/44

However, since fortinet.fortios does not run sanity tests either, this issue is still relevant and I will edit it for accuracy.

**Comment by JieX19** [comment]
@dmsimard  Thank you for letting us know. We will fix the issue ASAP.

**Comment by gundalow** [comment]
@JieX19 great thank you. If you have any questions we'd be happy to help. Just ask here.

**Comment by JieX19** [comment]
@dmsimard  I saw you run the sanity test on Python 2.7, which has syntax error complaints, but that actually works on Python 3. Do you still support and maintain python 2? If so, I need to fix this issue as well.

**Comment by dmsimard** [comment]
@JieX19 the current latest versions of ansible and ansible core require python >=3.8 on the controller side (where ansible/ansible-core are installed) but still support >=2.7 on the module/plugin side (executed on remote nodes).

I would say it depends which versions of python the collection itself is meant to support -- some collections no longer support python2 because underlying library requirements no longer support python2, for example.

**Comment by dmsimard** [comment]
Linking this issue to the community topic on sanity tests: https://github.com/ansible-community/community-topics/issues/96

The list of sanity test errors for this collection is available here: https://gist.githubusercontent.com/dmsimard/8da5dc6e3008c8051b7b1d21a067e9c4/raw/7753c796ea61b421f671c8feb8959074b52155ea/output.txt

**Comment by JieX19** [comment]
@dmsimard I saw this issue https://github.com/ansible/ansible/issues/67032, is it a hard requirement for all the collections to be licensed under GPL v3? Otherwise, it cannot pass the sanity-test due to missing-gplv3-license.

**Comment by dmsimard** [comment]
Apologies, I must have missed your message. I don't have immediate answers to your questions but I'll ask around.

Other than the two issues you've mentioned, have you been able to address the other sanity tests failures ? If possible, we'd appreciate if there could be a new release of the collection including the fixes so fortinet.fortios is clear for the release of ansible 6 soon.

**Comment by felixfontein** [comment]
@JieX19 the requirements for licensing can be found here: https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#id7

In case the collection does not satisfy them, you need to ask for an excemption, relicense that module, or remove it.

About the sanity test: the culprit is likely https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/blob/fos_v6.0.0/galaxy_2.1.2/plugins/modules/fortios_monitor_fact.py#L2968 it should probably be `choices`, but definitely not `options`. `options` needs to be a dictionary, not a list.

**Comment by felixfontein** [comment]
Actually I just saw that the module you mentioned is in fact a plugin: plugins/httpapi/fortios.py. Note that plugins import GPLv3+ licensed code from ansible-core, so they must be GPL licensed themselves. Otherwise they are in violation of the GPL.

You should probably check with your company's legal team. The easiest solution is probably to simply relicense that file under GPLv3+.

**Comment by gotmax23** [comment]
I did a quick license check for you and noticed two issues. I am also not a lawyer, so you should double check this and not take it as legal advice.

- galaxy.yml claims that the collection is MIT-licensed, but I didn't find any MIT license file or license header in the entire project.

I believe the license key should be

``` yaml
license:
  - GPL-3.0-or-later
  - BSD-2-Clause
```

- According to the Ansible Collection Requirements (@dmsimard linked them above), plugins/httpapi/fortios.py/fortios.py **needs to** be licensed under `GPL-3.0-or-later`.

**Comment by JieX19** [comment]
> 

Thanks for the help!

**Comment by JieX19** [comment]
> Apologies, I must have missed your message. I don't have immediate answers to your questions but I'll ask around.
> 
> Other than the two issues you've mentioned, have you been able to address the other sanity tests failures ? If possible, we'd appreciate if there could be a new release of the collection including the fixes so fortinet.fortios is clear for the release of ansible 6 soon.

@dmsimard I've fixed some errors like 'parameter-list-no-elements', but still need more time to address some other sanity-test issues. Your colleague recommend us to do a new release with the 'syntax error' bug fixes in the detected three modules.  Is it OK to do so?

**Comment by dmsimard** [comment]
@JieX19 right now 2.1.5 of fortinet.fortios causes a range of issues due to the syntax errors and so it is pinned to 2.1.4 in the Ansible community package.

If you are able to do a minor release (2.1.6?) including these fixes, we can unpin the version to allow users to pick up the latest updates while giving you some time to fix the remaining issues.

**Comment by JieX19** [comment]
@dmsimard  Thanks for your response. We will do a new release of 2.1.6 on 5/20/2022.

**Comment by Andersson007** [comment]
@JieX19 hello, how about the release 2.1.6 on 5/20/2022 ?

**Comment by JieX19** [comment]
@Andersson007 I saw our pm has approved the release today and the CM team is working on the release this afternoon. I will let you know once it's released successfully.

**Comment by JieX19** [comment]
@Andersson007  2.1.6 is available now.

**Comment by Andersson007** [comment]
@JieX19 there are still a lot of sanity failings
1. Clone https://github.com/ansible/ansible
2. cd ansible
3. source hacking/env-setup
4. cd <you collection dir>
5. ansible-test sanity --docker

Waiting for your feedback

**Comment by JieX19** [comment]
@Andersson007  Your colleagues recommended us to do a minor release including these syntax-error fixes. We've fixed them and some of the errors like 'parameter-list-no-elements'... but still need some time to fix the rest. 

One more question, how can I deal with the 'ImportError: No module named yaml'?

**Comment by Andersson007** [comment]
@JieX19 
>One more question, how can I deal with the 'ImportError: No module named yaml'?

The whole output of the ansible-test sanity command looks very strange to me. It looks like it doesn't work at all. I'm totally confused with what's going on there:)

**Comment by felixfontein** [comment]
See https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/testing/sanity/import.rst#import for the import errors.

**Comment by Andersson007** [comment]
@gotmax23 thanks!

@JieX19 using that branch and ansible-core stable-2.13 it returns so many errors that i can't past it here because `You can't comment at this time — your comment is too long (maximum is 65536 characters).`

**Comment by Andersson007** [comment]
@JieX19 yes, please fix them ASAP (as a temporary solution you can use an [ignore.txt](https://github.com/ansible-collections/community.general/blob/main/tests/sanity/ignore-2.14.txt) file but it must not contain entries listed in the [requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#ci-testing).

**Comment by JieX19** [comment]
Hi all,

The issues mentioned in this ticket have been addressed. I will close it at this moment and feel free to reopen it if you have any concerns.
