### ISSUE TITLE
Change order of Shaping-Policy

### ISSUE THREAD

**Issue by SEA-NET** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#190]
Hi there,

is there no way to change the order of items in the traffic shaping policy?
Firewall policies have "before:" and "after:" but I was not able to find a way to order shaper policies except to delete and recreate.

Did I miss something or is this the only way?

Thanks and best regards.

**Comment by alagoutte** [comment]
Hi @SEA-NET,

Missing the like for policy the possibility to move traffic shaping policy (there is like firewall policy an API for this !)

**Comment by JieX19** [comment]
Hi @SEA-NET,

I've added the 'move' operation in the module fortios_firewall_shaping_policy. It will be covered in the next release 2.1.7. I will let you know once released.

**Comment by JieX19** [comment]
Hi @SEA-NET,

The ‘move’ feature is supported in this module, https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_firewall_shaping_policy.html

I will close this issue at this moment and feel free to reopen it or open a new issue if you have any questions.
