### ISSUE TITLE
Backup config to file not working (FortiOS 6.4)

### ISSUE THREAD

**Issue by postmanGH** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#192]
Hi all,
I'm using ansible [core 2.12.7] and loaded in ansible-galaxy collection install fortinet.fortios:2.1.5 from this location https://galaxy.ansible.com/fortinet/fortios.

I do not get a config backup (to file) working using a ansible playbook.

I understand that 
`fortios_system_config_backup_restore:
      config: "system config backup"`

is legacy and the way to go is

`fortios_monitor_fact:
     selector: 'system_config_backup'`

Following this https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/75 
and 
https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-backup-and-restore-fos
i likely have put in a mistake, or since I am shooting this against a device running **FortiOS 6.4** (instead 6.2) something may have changed in FortiOS.

I am getting a 
`TASK [Backup a virtual domain.] **********************************************************************************************
fatal: [fortigate01]: FAILED! => {"changed": false, "meta": {"message": "unknown selector: system_config_backup"}, "msg": "Error in repo"}

PLAY RECAP *******************************************************************************************************************
fortigate01  ﻿              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0`

I can make changes to the same device / Fortigate config using a different playbook / the same inventory and such, but i don't get the config backup working.

Also switching galaxy collections by "ansible-galaxy collection install -f fortinet.fortios:1.1.7" do not make it fly.

Any advise is highly appreciated. Thanks in advance.

**Comment by JieX19** [comment]
Hi @postmanGH 

It's the same question as https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/186. Can you please follow the steps to upgrade the FOS version and collection version?

**Comment by postmanGH** [comment]
Hello @JieX19 , thanks a lot.

I indeed overlooked that one, thanks for pointing to #186  . I can confirm ansible collection of 2.1.4 is working with FortiOS 6.4.8 / 6.4.9 and will check out 7.x.x using 2.1.6 / fortios_monitor.
