### ISSUE TITLE
Collection Requirements Violation - Repository Management

### ISSUE THREAD

**Issue by gotmax23** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#207]
Hi! The Ansible Community Steering Committee has determined that this collection does not tag its releases in its git repository. This violates the [repository management](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#repository-management) section of the Collection Requirements:

> Every collection MUST have a public git repository. Releases of the collection MUST be tagged in said repository. This means that releases MUST be `git tag`ed and that the tag name MUST exactly match the Galaxy version number. Tag names MAY have a `v` prefix, but a collection's tag names MUST have a consistent format from release to release.
>
> Additionally, collection artifacts released to Galaxy MUST be built from the sources that are tagged in the collection's git repository as that release. Any changes made during the build process MUST be clearly documented so the collection artifact can be reproduced.

Note that this requirement has recently [been clarified](https://github.com/ansible-collections/overview/commit/6dbb5037c09dce9324cb39e322be2f42e068f117), but its intent remains the same. Please tag at least the previous 1-2 releases of your collection to come into compliance. I understand that this collection currently stores each release in a separate branch, but that does not meet this requirement.

Please keep us updated and let us know if you have any questions. Thanks!

**Comment by lix-fortinet** [comment]
Hi @gotmax23,

Thank you for your notification. We will update it in next release.

Thanks,
Xing

**Comment by gotmax23** [comment]
Great! Please also `git tag` the last two releases. E.g. for 2.1.7 (https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/commit/8ec95ea5b4925eda4ce46bbfde9b1ea05168dfe4), run 

```
git tag  2.1.7 8ec95ea5b4925eda4ce46bbfde9b1ea05168dfe4
```

and push.

**Comment by lix-fortinet** [comment]
Sure, no problem.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @gotmax23,

We added the tags for v2.1.7 and v2.2.0.

Please let me know if you have any other requirements.

Thanks,
Xing

**Comment by gotmax23** [comment]
Nope, this looks good to me! Thanks for fixing it.

**Comment by gotmax23** [comment]
Please don't forget to do the same for https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/issues/53.
