### ISSUE TITLE
fortios_configuration_fact - selector: system_interface - does not provide all macaddresses. 

### ISSUE THREAD

**Issue by patrickpreuss** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#234]
With collection: fortinet.fortios:2.2.2 
Fortigate 60E / OS 7.2.4 

and task
  - name: Get multiple selectors info concurrently
    fortios_configuration_fact:
        selectors:
        - selector: system_interface
   when: ansible_network_os == 'fortinet.fortios.fortios'
    register: fortios

only interface "internal" does contain a macaddress.

**Comment by MaxxLiu22** [comment]
I will go ahead to close this case, if you still have questions, feel free to reopen it or another case.
