### ISSUE TITLE
Cannot set multiple member_paths

### ISSUE THREAD

**Issue by cwilliams-intelerad** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#243]
Unable to set multiple member_path. Sure this is the same in many modules but I am working on fortios_firewall_policy in particular.  I receive an error message on the second member_path no matter what it is. Am I using the correct syntax? If not, what is correct way to maintain state of multiple paths in same module?

Error: "msg": "Attribute dstinf not as part of module schema"

Code:

`---
- name: Create firewall policy
  fortinet.fortios.fortios_firewall_policy:
    vdom: "{{ vdom }}"
    state: "{{ state }}"
    member_path: dstaddr:name / dstinf:name / srcaddr:name / srcintf:name / service:name
    member_state: present
    firewall_policy:
      policyid: "{{ policyid }}"
      action: "{{ action }}"
      comments: "{{ comment | default(omit) }}"
      dstaddr: "{{ dstaddrs }}"
      dstintf: "{{ dstintfs }}"
      srcaddr: "{{ srcaddrs }}"
      srcintf: "{{ srcintfs }}"
      service: "{{ services }}"`
      schedule: "{{ schedule }}"

**Comment by JieX19** [comment]
Hi @cwilliams-intelerad,

Multiple member_paths are not supported currently, FYI, https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.1.6/gen/fortios_firewall_policy.html, and https://ansible-galaxy-fortios-docs.readthedocs.io/en/2.2.3/faq.html#how-to-use-the-member-operation-to-add-an-element-in-an-object

The slash "/" is used for the recursive path in the module. 

In your case, you can run multiple tasks in a playbook to add elements to each object.

Thanks,
Jie

**Comment by cwilliams-intelerad** [comment]
I see. Thank you for the quick response!
