### ISSUE TITLE
Too much no_log since 2.1.7

### ISSUE THREAD

**Issue by simonpahl** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#248]
Since version 2.1.7 all sub arguments seem to be in no_log mode. In version 2.1.6 the output was more verbose.
I suspect https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/blob/main/plugins/module_utils/fortios/fortios.py#L83 to be the cause.

I cannot see if this is intended or a bug, but it seems to make any output hardly readable.

**Comment by MaxxLiu22** [comment]
Hi @simonpahl ,

This is intended in order to satisfy ansible community requirement, we will improve this part to have a better experience.

Thanks,
Maxx

**Comment by simonpahl** [comment]
Thanks for the clarification.
