### ISSUE TITLE
I have created a yaml file which is pause.yml. I have created a playbook and when i am trying to execute the playbook , it is showing me an error :       An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None fatal: [localhost]: FAILED! => {"msg": "Unsupported parameters for (ansible_collections.ansible.builtin.plugins.action.debug) module: seconds. Supported parameters include: msg, var, verbosity."} 

### ISSUE THREAD

**Issue by Sunny2609** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#261]
// This is the pause.yml file i have written .
---
- name: pause module demo
  hosts: localhost
  vars:
    wait_seconds: 10
  tasks:
    - name: pause for {{ wait_seconds | int }} second(s)
      ansible.builtin.debug:
        seconds: "{{ wait_seconds | int }}"
          
          
          
    - name: message
      ansible.builtin.debug:
        msg: "The end"
      verbosity: 2

**Comment by JieX19** [comment]
Hi @Sunny2609 

The error message " {"msg": "Unsupported parameters for (ansible_collections.ansible.builtin.plugins.action.debug) module: seconds " means the parameter 'seconds' is not supported in the module.

I checked the doc of ansible.builtin.debug module, https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html, you can see all the supported params here. ONLY msg, verbosity, and var are available in this module.

You may refer to https://www.ansiblepilot.com/articles/pause-execution-ansible-module-pause/, hope this helps.

**Comment by JieX19** [comment]
Hi @Sunny2609 

I will close the issue at this moment, marking it as resolved or completed. If you have any further questions or concerns, please feel free to reopen the ticket or create a new one.
