### ISSUE TITLE
module fortios_monitor using selector: 'upgrade.system.firmware' 

### ISSUE THREAD

**Issue by Ben-Sassi-Oussema** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#267]
"I want to upgrade my device from version 6.4.7 to version 7.0.12. I used the firmware image 'FGT_VM64-v7.0.12.M-build0523-FORTINET.out.' However, after running my playbook, the device was not upgraded , and I'm unsure why it didn't upgrade to version 7.0.12."

playbook log: 
ok: [device1] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "enable_log": false,
            "params": {
                "file_content": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48RXJyb3I+PENvZGU+QWNjZXNzRGVuaWVkPC9Db2RlPjxNZXNzYWdlPkFjY2VzcyBEZW5pZWQ8L01lc3NhZ2U+PFJlc291cmNlPjwvUmVzb3VyY2U+PFJlcXVlc3RJZD42MWI1NDdhMzczNDE4M2UxMmE0YzwvUmVxdWVzdElkPjwvRXJyb3I+",
                "filename": "FGT_VM64-v7.0.12.M-build0523-FORTINET.out",
                "format_partition": true,
                "ignore_invalid_signature": false,
                "source": "upload"
            },
            "selector": "upgrade.system.firmware",
            "vdom": "root"
        }
    },
    "meta": {
        "action": "upgrade",
        "build": 1911,
        "http_method": "POST",
        "name": "firmware",
        "path": "system",
        "results": {
            "error": {
                "code": -593,
                "message": "-593"
            },
            "status": "error"
        },
        "serial": "FGV**********",
        "status": "success",
        "vdom": "root",
        "version": "v6.4.7"
    }
}

i used this playbook:
  - name: Update Firmware
    fortinet.fortios.fortios_monitor:
        selector: 'upgrade.system.firmware'
        access_token: "{{ fortios_access_token | default(omit) }}"
        vdom: "{{ vdom | default('root') }}"
        params:
          source: "upload"
          filename: "{{image_name}}"
          file_content: "{{ lookup('file', '../image/' + image_name) | string | b64encode }}"
          format_partition: true
          ignore_invalid_signature: false

**Comment by JieX19** [comment]
Hi @Ben-Sassi-Oussema，

I can reproduce the issue you mentioned. I tested the module with the Ansible fortiOS collection 2.3.0 and it works. I will look into the issue and it will be fixed in the next release.
