### ISSUE TITLE
7.4.1 Foritnet OS is not supported

### ISSUE THREAD

**Issue by sirrus** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#269]
Please add support for 7.4.1

I would like to suggest a general fallback to the latest supported version for unknown versions.

Kind regards

**Comment by JieX19** [comment]
Hi @sirrus 

Thanks for your suggestion! We regularly update the FOS collection every two months if there are nothing urgent fixes. It will be a new release next month. Thank you very much for your patience! May I know any APIs you want to use? Are they exclusive to 7.4.1? I can double-check for you.

**Comment by sirrus** [comment]
@JieX19 
The same api as on 7.4.0 - so no additional api yet.
Thank you

**Comment by JieX19** [comment]
Hi @sirrus 

7.4.1 is supported in the latest version 2.3.4, please try it again. I will close the issue at this moment, marking it as resolved or completed. If you have any further questions or concerns, please feel free to reopen the ticket or create a new one.
