### ISSUE TITLE
Adding new router_static with seq_num=0 does not work since 2.3.1

### ISSUE THREAD

**Issue by jplitza** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#278]
Since release 2.3.1, there is some code that first looks for the given static route on the device, and fails when i pass seq_num=0. In release 2.3.0, this still works, but I have to specify seq_num=0 explicitly (compared to earlier versions where 0 was the implicit default).

(I know the implications of using seq_num=0 and explicitly want to add a new entry without caring about what ID it is assigned.)

**Comment by JieX19** [comment]
Hi @jplitza 

Please try the latest version 2.3.6 and try this module again. I'll proceed to close this ticket as it has been fixed.

Thanks,
Jie

**Comment by zeljko-ciric** [comment]
This issue reappears again in 2.3.9
