### ISSUE TITLE
config system globals timezone not numeric in 7.4.2

### ISSUE THREAD

**Issue by diLLec** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#290]
Hi there,

the parameter "timezone" is not numeric in 7.4.2 anymore.

```
fw02 (global) # set timezone 26
entry not found in datasource

value parse error before '26'
Command fail. Return code -3
```

The value needs to be a qualified string like Europe/Berlin to work well

```
config system global
    set timezone "Europe/Berlin" <---
end
``

**Comment by diLLec** [comment]
The problem is, that plugins/modules/fortios_system_global.py does not allow those values yet.

**Comment by MaxxLiu22** [comment]
Hi @diLLec ,

Thank you for raising this issue, our FOS ansible collection currently supports until 7.4.1, we will upgrade our FOS collection to be compatible with latest FOS version soon, sorry for any inconvenience.

Thanks,
Maxx

**Comment by JieX19** [comment]
Hi @diLLec 

Please install the latest collection version 2.3.6 and try this module again. I'll close this ticket because the issue has been fixed in this version. Feel free ti reopen it if you still experience the same issue.

Thanks,
Jie
