### ISSUE TITLE
system_arp_table need to search for a mac address

### ISSUE THREAD

**Issue by chr00ted** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#324]
I need to find a MAC in the arp table on several firewalls. On Cisco Switches I was able to do it with:

ios_command:

        commands:

          - "show mac address-table | include {{ mac }}"

      register: printout

What is the best way to do that with system_arp_table module?

I can manually goto each fw and run: get sys arp | grep macaddressimlookingfor

**Comment by MaxxLiu22** [comment]
Hi @chr00ted ,

Thank you for your question. If we would like to query some information or configuration from FortiOS (FOS), we typically use [Monitor Modules](https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/monitor.html) or [Facts Gathering Modules](https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fact.html). You just need to define the selector you want to use. Please let me know if this doesn't solve your question.

```
  tasks:
  - fortios_monitor_fact:
       vdom: "root"
       enable_log: true
       selector: 'network_arp'
    register: arp
  - debug: msg="{{ arp }}"  
    name: arp table
```

Thanks,
Maxx

**Comment by chr00ted** [comment]
Hey Max, this is only giving me interface mac address, I would like the the ability, if possible, to check the system arp for connected devices mac addresses. I can manually run this on a fortinet by doing: get sys arp
Additionally if Iim search for a specific mac i can run: get sys arp | grep macaddressimlookingfor

Is this possible via ansible? I didnt see a selector for system_arp

**Comment by dominicfillmore** [comment]
I just tried what Maxx suggested and got the contents of the ARP table. It's the same data I get by using 'get sys arp' in JSON.
Have you specified the right VDOM in the play?

**Comment by MaxxLiu22** [comment]
Hi @chr00ted ,

Could you please take a look at this task? There might be some differences in function names between the CLI and API. Additionally, as @dominicfillmore mentioned, could you kindly double-check if you are querying the desired VDOM.
```
  - fortios_configuration_fact:
      vdom: "root"
      selector: 'system_arp'
    register: system_arp
  - debug: msg="{{ system_arp }}"  
    name: system arp table
```
Thanks,
Maxx

**Comment by chr00ted** [comment]
Sure, going to test it now. Thanks Maxx

**Comment by chr00ted** [comment]
The job runs, but I'm not seeing any arp info in the JSON and I am using your play:

{
  "msg": {
    "changed": false,
    "meta": {
      "http_method": "GET",
      "revision": "8419b4fac8e5d5161b496fb9482816fc",
      "results": {},
      "vdom": "root",
      "path": "system",
      "name": "arp",
      "status": "success",
      "http_status": 200,
      "serial": "FGremoved",
      "version": "v7.2.7",
      "build": 1577
    },
    "failed": false
  },
  "_ansible_verbose_always": true,
  "_ansible_no_log": false,
  "changed": false
}

**Comment by chr00ted** [comment]
I got it working using your original play, @dominicfillmore  was right the results are in the JSON. Thanks
