### ISSUE TITLE
KeyError: 'ldb_method' with --check

### ISSUE THREAD

**Issue by milad-24** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#330]
I got this error when I ran my Ansible playbook with --check parameter.

```
TASK [fortigate : virtual server] *********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'ldb_method'
```

**Comment by MaxxLiu22** [comment]
Hi @milad-24 ,

Thank you for raising this issue, the difference check function has some issue in Ansible FOS 2.3.6, please upgrade to Ansible FOS 2.3.7 and give a try, sorry for the inconvenience. Let me know if the issue still exists.
```
ansible-galaxy collection install fortinet.fortios:2.3.7
```
Thanks,
Maxx

**Comment by milad-24** [comment]
I tried fortinet.fortios:2.3.7 and as I see the error is resolved! 
Thank you.
