### ISSUE TITLE
fortios_system_vmlicense module throwing error

### ISSUE THREAD

**Issue by razikhussein** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#34]
[2020-06-25 02:46:13,970] {ans_handler:68} DEBUG - ansible playbook task conf_license : Wait timer for vFW instance readiness run OK: {'state': 'started', 'port': None, 'search_regex': None, 'match_groups': [], 'match_groupdict': {}, 'path': None, 'elapsed': 90, 'invocation': {'module_args': {'timeout': 90, 'host': '127.0.0.1', 'connect_timeout': 5, 'delay': 0, 'active_connection_states': ['ESTABLISHED', 'FIN_WAIT1', 'FIN_WAIT2', 'SYN_RECV', 'SYN_SENT', 'TIME_WAIT'], 'state': 'started', 'sleep': 1, 'port': None, 'path': None, 'search_regex': None, 'exclude_hosts': None, 'msg': None}}, '_ansible_no_log': False, 'changed': False}
[2020-06-25 02:46:13,979] {ans_handler:155} DEBUG - ansible playbook task Configure License started:
[2020-06-25 02:46:17,295] {ans_handler:142} ERROR - task: 'conf_license : Configure License' FAILED: MODULE FAILURE
See stdout/stderr for the exact error, [{'task': 'conf_license : Configure License', 'result': {'module_stdout': '', 'module_stderr': 'Traceback (most recent call last):\n  File "/root/.ansible/tmp/ansible-local-10nuh0gds4/ansible-tmp-1593053176.7907958-124938959598587/AnsiballZ_fortios_system_vmlicense.py", line 102, in <module>\n    _ansiballz_main()\n  File "/root/.ansible/tmp/ansible-local-10nuh0gds4/ansible-tmp-1593053176.7907958-124938959598587/AnsiballZ_fortios_system_vmlicense.py", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File "/root/.ansible/tmp/ansible-local-10nuh0gds4/ansible-tmp-1593053176.7907958-124938959598587/AnsiballZ_fortios_system_vmlicense.py", line 40, in invoke_module\n    runpy.run_module(mod_name=\'ansible.modules.fortios_system_vmlicense\', init_globals=None, run_name=\'__main__\', alter_sys=True)\n  File "/usr/local/lib/python3.6/runpy.py", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/modules/fortios_system_vmlicense.py", line 284, in <module>\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/modules/fortios_system_vmlicense.py", line 262, in main\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/modules/fortios_system_vmlicense.py", line 225, in fortios_system\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/modules/fortios_system_vmlicense.py", line 214, in system_vmlicense\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 200, in execute\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Expecting value: line 1 column 1 (char 0)\n', 'exception': 'Traceback (most recent call last):\n  File "/root/.ansible/tmp/ansible-local-10nuh0gds4/ansible-tmp-1593053176.7907958-124938959598587/AnsiballZ_fortios_system_vmlicense.py", line 102, in <module>\n    _ansiballz_main()\n  File "/root/.ansible/tmp/ansible-local-10nuh0gds4/ansible-tmp-1593053176.7907958-124938959598587/AnsiballZ_fortios_system_vmlicense.py", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File "/root/.ansible/tmp/ansible-local-10nuh0gds4/ansible-tmp-1593053176.7907958-124938959598587/AnsiballZ_fortios_system_vmlicense.py", line 40, in invoke_module\n    runpy.run_module(mod_name=\'ansible.modules.fortios_system_vmlicense\', init_globals=None, run_name=\'__main__\', alter_sys=True)\n  File "/usr/local/lib/python3.6/runpy.py", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/modules/fortios_system_vmlicense.py", line 284, in <module>\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/modules/fortios_system_vmlicense.py", line 262, in main\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/modules/fortios_system_vmlicense.py", line 225, in fortios_system\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/modules/fortios_system_vmlicense.py", line 214, in system_vmlicense\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 200, in execute\n  File "/tmp/ansible_fortios_system_vmlicense_payload_wgqcsmws/ansible_fortios_system_vmlicense_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Expecting value: line 1 column 1 (char 0)\n', 'msg': 'MODULE FAILURE\nSee stdout/stderr for the exact error', 'rc': 1, '_ansible_no_log': False, 'changed': False}}]
[2020-06-25 02:46:17,319] {ans_handler:270} DEBUG - request 5f0b15a9-bf82-4fdd-b53e-e6fff3315b84 action Configure ansible facts{"state": "started", "port": null, "search_regex": null, "match_groups": [], "match_groupdict": {}, "path": null, "elapsed": 90, "invocation": {"module_args": {"timeout": 90, "host": "127.0.0.1", "connect_timeout": 5, "delay": 0, "active_connection_states": ["ESTABLISHED", "FIN_WAIT1", "FIN_WAIT2", "SYN_RECV", "SYN_SENT", "TIME_WAIT"], "state": "started", "sleep": 1, "port": null, "path": null, "search_regex": null, "exclude_hosts": null, "msg": null}}, "_ansible_no_log": false, "changed": false}
[2020-06-25 02:46:17,320] {ans_handler:362} ERROR - request 5f0b15a9-bf82-4fdd-b53e-e6fff3315b84 action Configure FAILED:conf_license : Configure License resource tasks failed failure code:

**Comment by razikhussein** [comment]
I have tested this with 1.0.9 earlier in another server and it was working fine.
In the current server I installed 1.0.13 and getting error above. When I revert back to 1.0.9 then it works.

**Comment by chillancezen** [comment]
hi @razikhussein , 

thanks for your issue.


 for licensed Fortgates, I ran playbooks with Galaxy 1.0.13 for FOS 6.0, 6.2 and 6.4. all them work fine.
    
```
- hosts: fortigate01
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   license_file: ./FortiOS.lic
   license_file_content: "{{ lookup( 'file', license_file) }}"
   encoded_license: "{{ license_file_content | string | b64encode }}"
  tasks:
  - name: Update VM license using uploaded file. Reboots immediately if successful.
    fortios_system_vmlicense:
      vdom:  "{{ vdom }}"
      system_vmlicense:
        file_content: "{{ encoded_license }}"
```
the error  in your description must be targeting an unlicensed Fortigate device.

for unlicensed Fortgates,  could you please help provide the following info for us do further reproduction?
1) Fortigate device version
2) is the FortiGate device which you are targeting licensed?
3) the playbook and the host inventory.
4) output of `ansible --version`.

thanks,
Link

**Comment by chillancezen** [comment]
with latest FortiOS galaxy collection, please see the doc: https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-import-a-license for more.

mark it `closed`, feel free to reopen. 

thanks.
