### ISSUE TITLE
fortinet.fortios.fortios_configuration_fact | Selector: "system_status" | "msg": "Error in repo" | fortios version 2.3.6

### ISSUE THREAD

**Issue by iskadzul123** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#340]
Hi Team,

I am new to ansible and this is my first time posting on this forum do pardon me for any clarity issues. I tried the following function 
 - system_status

and its giving me the following error message,
TASK [Print Devices Hostname] ********************************************************************************************
fatal: [FG4]: FAILED! => {"changed": false, "meta": {"build": 2662, "http_method": "GET", "http_status": 404, "name": "status", "path": "system", "serial": "FGVMEV3MNVIZVL96", "status": "error", "version": "v7.4.4"}, "msg": "Error in repo"}

I think it is a bug issue.

**Comment by MaxxLiu22** [comment]
Hi @iskadzul123 ,

Thank you for bringing this issue to our attention. To support the changes in FOS 7.4.4, we have moved some features from fortios_configuration_fact to fortios_monitor_fact. Could you please use fortios_monitor_fact to acquire the system status? Additionally, we have identified some compatibility issues between Ansible FOS 2.3.6 and Ansible-core 2.17.0. We kindly suggest upgrading to version 2.3.7 at your earliest convenience to avoid any potential issues in the future.
```
ansible-galaxy collection install fortinet.fortios:2.3.7
```
```
  tasks:
  - fortios_monitor_fact:
       vdom: "root"
       enable_log: true
       selector: 'system_status'
```

Thanks,
Maxx
