### ISSUE TITLE
fortinet.fortios.fortios_firewall_addrgrp & json input

### ISSUE THREAD

**Issue by chr00ted** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#344]
Hello, I'm looking to add a group to other groups and I was wondering if I could use JSON for it. When I try it seems to fail, am I doing this right or should I change anything. Thanks in advance!

FYI: vdom = root & nname is my group name: TEST-GRP-NEW

`  - name: Read groups from JSON
    set_fact:
      site_groups: "{{ lookup('file', 'site_groups.json') | from_json }}"

   - name: Add New Location - Update Site Group
    fortinet.fortios.fortios_firewall_addrgrp:
      vdom: "{{ vdom }}"
      state: "present"
      member_state: "present"
      member_path: "member:name"
      firewall_addrgrp: 
         allow_routing: "enable"
         fabric_object: "enable"
         name: "{{ item }}"
         member:
            - name: "{{ nname }}"
    loop: "{{ site_groups }}"`

site_groups.json (I have more groups to add to the JSON provided it works:
`[
    "US - All Sites",
    "Remote Networks - FTL"
]`

**Comment by chr00ted** [comment]
I'm thinking it has to deal with the group names having spaces

**Comment by MaxxLiu22** [comment]
Hi @chr00ted ,

Thank you for bringing this issue to our attention. I was able to reproduce the problem and have noted that Ansible FOS currently restricts the use of spaces in URLs. However, it should accommodate them. I have reported this to the development team for resolution. I sincerely apologize for any inconvenience this may have caused.

Thanks,
Maxx

**Comment by chr00ted** [comment]
Cool, thanks @MaxxLiu22
