### ISSUE TITLE
Why append member option missing for fortios_firewall_addrgrp

### ISSUE THREAD

**Issue by ginigangadharan** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#36]
Thank you for this collection and modules.

But, it seems a major feature is missing for fortios_firewall_addrgrp.py.
We can add Address Groups but it will keep only the members we mention there.
What if there is 100 member address/groups in Address Group and we want to `append` 1 or 2 members ? 

I can append members from console as below; means the feature is available on device but we missed to include in module.
` append member test1-10.2.10.0-24`

Could anyone please advise if there is an option to append with same module ?
or any other module I can use append a member to Address Group ?

Thank you.

**Comment by ginigangadharan** [comment]
To Add :

I am using `raw` module to achieve this now.

```
   - name: Config
      raw: |
            config firewall addrgrp
            edit blklist1
            append member test1-10.2.10.0-24
            end
```

**Comment by chillancezen** [comment]
thanks @ginigangadharan for the issue.

all APIs an Fortigate device exports for Ansible have only `set` semantics, which means we must update/create an object at one go. Unfortunately we don't have available support to address the requirement above. 

very glad to know you have the workaround by using `raw`,  officially, we also have generic module to do the same work:
https://github.com/fortinet/ansible-fortios-generic

thanks,
Link

**Comment by ginigangadharan** [comment]
@chillancezen Thants awesome !
I was looking for a such thing all over; thank you for that.

Okay, also noted on that API support thing.

I will mark this issue as closed for now :)

**Comment by unbreakabl3** [comment]
> thanks @ginigangadharan for the issue.
> 
> all APIs an Fortigate device exports for Ansible have only `set` semantics, which means we must update/create an object at one go. Unfortunately we don't have available support to address the requirement above.
> 
> very glad to know you have the workaround by using `raw`, officially, we also have generic module to do the same work: https://github.com/fortinet/ansible-fortios-generic
> 
> thanks, Link

There is an option called "append" exists now in FortiOS 6.4.10 at least. Is it possible to add this to the fortios_firewall_addrgrp module?

![image](https://user-images.githubusercontent.com/13556249/195578442-0f330749-5803-4f47-9cfd-81545b1350da.png)

**Comment by lix-fortinet** [comment]
Hi @unbreakabl3,

Thank you for your comment. The `append` command is not a new operation of FortiOS v6.4.10. It is an CLI command. But there is no REST API for this functionality. So, we still recommend users to use the solution listed in the previous comments. 

Thanks,
Xing

**Comment by unbreakabl3** [comment]
Hi, @lix-fortinet ,
thank you very much for your quick reply. 

This REST API call is adding a new member to the group. Tested on 6.4.x

- name: Add new server to the {{ firewall_address_group }} group
  uri:
    url: https://{{ hostname }}/api/v2/cmdb/firewall/addrgrp/{{ group }}/member?access_token={{ api_access_token }}
    method: POST
    body_format: json
    body: |
      {
        "name": "{{ address }}"
      }

**Comment by ginigangadharan** [comment]
@unbreakabl3 and @lix-fortinet 
Thank you for that. Will wait for the update.

**Comment by lix-fortinet** [comment]
Hi @unbreakabl3,

Thank you for your update. You are welcome to use this as your workaround or by the generic module mentioned by [chillancezen](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/36#issuecomment-655406250):  https://github.com/fortinet/ansible-fortios-generic. We will keep an eye on this request, and will get back to you once we have any improvement.

Thanks,
Xing

**Comment by sebypp** [comment]
Hi,

Having fought with this myself, it's actually documented [here](https://ansible-galaxy-fortios-docs.readthedocs.io/en/stable/faq.html#how-to-use-the-member-operation-to-add-an-element-in-an-object).

Find an example below
```yaml
- name: Append to address group
  fortinet.fortios.fortios_firewall_addrgrp:
    vdom: "root"
    state: present
    member_state: present
    member_path: member:name
    firewall_addrgrp:
      name: "TEST-GROUP"
      member:
        - name: none
```

Notice that `member:name` should be remain as is.

Teste on FortiOS 7.2.0

**Comment by bogd** [comment]
> Notice that `member:name` should be remain as is.

Does not seem to be working for me (FortiOS 7.6.0) . I get an "ok" (when it should be "changed"), and no change is performed on the device.

```
  - name: Add address to group
    fortinet.fortios.fortios_firewall_addrgrp:
      vdom: root
      state: present
      member_state: present
      member_path: member:name
      firewall_addrgrp:
        name: GROUP_NAME
        member:
        - name: "ADDRESS_{{ '_'.join(new_ip.split('.')) }}"
    register: forti_result
```
Even though the task returns "ok", the result is actually an HTTP 401 Unauthorized:

```
ok: [fortigate] => {
    "forti_result": {
        "changed": false,
        "failed": false,
        "meta": [
            {
                "http_status": 401,
                "object_path": "/firewall/addrgrp/GROUP_NAME/member/ADDRESS_1_1_1_1",
                "raw": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>401 Unauthorized</title>\n</head><body>\n<h1>Unauthorized</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn't understand how to supply\nthe credentials required.</p>\n<p>Additionally, a 401 Unauthorized\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n"
            }
        ]
    }
}
```

The credentials are fine, the actual address is created in a previous step without any issues.

**Comment by MaxxLiu22** [comment]
Hi @bogd ,

Thank you for bringing this issue to my attention. The script runs well on my end, and it successfully adds a created address ``ADDRESS_1_1_1_2`` to an existing address group ``TEST_GROUP``. Could you kindly let me know which Ansible FOS version you are using? If possible, would you mind providing the debug output by adding -vvv to your command ``ansible-playbook -i hosts fortios_firewall_addrgrp.yml -vvv``?
```
ansible.netcommon                        7.0.0  
ansible.utils                            5.0.0  
fortinet.fortios                         2.3.7 
```
```
changed: [fortigate03] => {
    "changed": true,
    "diff": {},
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": false,
            "firewall_address": {
                "allow_routing": "enable",
                "associated_interface": "port1",
                "cache_ttl": 5,
                "clearpass_spt": "unknown",
                "color": 7,
                "comment": "Comment.",
                "country": null,
                "end_ip": null,
                "end_mac": null,
                "epg_name": null,
                "fabric_object": null,
                "filter": null,
                "fqdn": null,
                "fsso_group": null,
                "hw_model": null,
                "hw_vendor": null,
                "interface": null,
                "list": null,
                "macaddr": [
                    {
                        "macaddr": "00:00:5e:00:53:af"
                    },
                    {
                        "macaddr": "00:00:5e:00:53:aa"
                    }
                ],
                "name": "ADDRESS_1_1_1_2",
                "node_ip_only": null,
                "obj_id": null,
                "obj_tag": null,
                "obj_type": null,
                "organization": null,
                "os": null,
                "policy_group": null,
                "route_tag": null,
                "sdn": null,
                "sdn_addr_type": null,
                "sdn_tag": null,
                "start_ip": null,
                "start_mac": null,
                "sub_type": null,
                "subnet": null,
                "subnet_name": null,
                "sw_version": null,
                "tag_detection_level": null,
                "tag_type": null,
                "tagging": null,
                "tenant": null,
                "type": "mac",
                "uuid": null,
                "visibility": null,
                "wildcard": null,
                "wildcard_fqdn": null
            },
            "member_path": null,
            "member_state": null,
            "state": "present",
            "vdom": "root"
        }
    },
    "meta": {
        "action": "",
        "build": 3401,
        "http_method": "POST",
        "http_status": 200,
        "mkey": "ADDRESS_1_1_1_2",
        "name": "address",
        "old_revision": "5a5ec9ba6a007befd1587c067ef70e82",
        "path": "firewall",
        "revision": "31c9276041fd3647a2f4b1f96c0b36a8",
        "revision_changed": true,
        "serial": "FGVMULTM24000867",
        "status": "success",
        "vdom": "root",
        "version": "v7.6.0"
    }
}
changed: [fortigate03] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": false,
            "firewall_addrgrp": {
                "allow_routing": null,
                "category": null,
                "color": null,
                "comment": null,
                "exclude": null,
                "exclude_member": null,
                "fabric_object": null,
                "member": [
                    {
                        "name": "ADDRESS_1_1_1_2"
                    }
                ],
                "name": "TEST_GROUP",
                "tagging": null,
                "type": null,
                "uuid": null,
                "visibility": null
            },
            "member_path": "member:name",
            "member_state": "present",
            "state": "present",
            "vdom": "root"
        }
    },
    "meta": [
        {
            "action": "",
            "build": 3401,
            "child_path": "member",
            "http_method": "POST",
            "http_status": 200,
            "mkey": "ADDRESS_1_1_1_2",
            "name": "addrgrp",
            "object_path": "/firewall/addrgrp/TEST_GROUP/member/ADDRESS_1_1_1_2",
            "old_revision": "01c72dd529457dcff073db94f8686e11",
            "path": "firewall",
            "revision": "8ea20964b72c18dad6a7e19ff09b6ea9",
            "revision_changed": true,
            "serial": "FGVMULTM24000867",
            "status": "success",
            "vdom": "root",
            "version": "v7.6.0"
        }
    ]
}
```

Thanks,
Maxx

**Comment by bogd** [comment]
> Thank you for bringing this issue to my attention. The script runs well on my end, and it successfully adds a created address `ADDRESS_1_1_1_2` to an existing address group `TEST_GROUP`. 

Thank you for the quick reply! 

In my case, it appears it was a classical case of PICNIC (Problem In Chair, Not In Computer) :) . When collecting the log data you requested, I noticed that when writing my task (listed above), I forgot to add the `access_token` argument. 

After adding the access_token, the tasks executes successfully:
```
ok: [fortigate] => {
    "forti_result": {
        "changed": false,
        "failed": false,
        "meta": [
            {
                "action": "",
                "build": 3401,
                "child_mkey": "ADDRESS-1-1-1-1",
                "child_path": "member",
                "http_method": "PUT",
                "http_status": 200,
                "mkey": "ADDRESS-1-1-1-1",
                "name": "addrgrp",
                "object_path": "/firewall/addrgrp/BLOCKED_IPS/member/ADDRESS-1-1-1-1",
                "path": "firewall",
                "revision": "653d59fa07d9181b0a58bd88cd6f8366",
                "revision_changed": false,
                "status": "success",
                "vdom": "root",
                "version": "v7.6.0"
            }
        ]
    }
}
```

There is still a problem with the module (it definitely should not report `ok` when the underlying result is a 401 Unauthorized). But the main issue here was me forgetting the authentication details.

Once again, thank you!

**Comment by MaxxLiu22** [comment]
Hi @bogd ,

Thank you for your reply. We appreciate your feedback and will work on improving this aspect to ensure users receive the correct information for debugging. We are also aware of the issue where users need to provide an access token for every task, which is not our intended experience. Our goal is for users to provide their credentials once at the first task, with these being automatically applied to subsequent tasks. We will address this issue in the next release to enhance the overall user experience.

Thanks,
Maxx
