### ISSUE TITLE
vpn_ipsec_phase1_interface does not accept listed proposal values

### ISSUE THREAD

**Issue by kphillipsjr1101** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#48]
I have a role I've created in order to configure some VPNs and in testing the role I was met with the following error:

`fatal: [hostname]: FAILED! => {"changed": false, "msg": "value of proposal must be one of: des-md5, des-sha256, des-sha384, des-sha512, got : aes256-sha1 found in vpn_ipsec_phase1_interface"}`

From what I see in the documentation I should definitely be able to use this proposal. Even going through the associated .py file lists aes256-sha1 as an accepted proposal on the list.

This behavior is seen across both the 1.0.11 and 1.0.13 versions.

I have confirmed that the playbook below works outside of the role when called from a static single playbook, but when called from a role I am met with the error above.

Below is the playbook that I'm having issues with:

```
---
- name: configure phase1 ipsec vpn (primary)
  fortios_vpn_ipsec_phase1_interface:
    vdom: "{{ vdom }}"
    state: "present"
    vpn_ipsec_phase1_interface:
      name: "phase1interface"
      comments: "Phase 1 VPN Interface "
      interface: "wan"
      type: "ddns"
      remotegw_ddns: "vpnhostname"
      nattraversal: "forced"
      ike_version: "2"
      peertype: "any"
      net_device: "disable"
      proposal: "aes256-sha1"
      dhgrp: "21"
      psksecret: "Testpassword"

- name: configure phase2 ipsec vpn (primary) user
  fortios_vpn_ipsec_phase2_interface:
    vdom: "{{ vdom }}"
    state: "present"
    vpn_ipsec_phase2_interface:
      name: "phase2name"
      comments: "Attached phase2 interface"
      phase1name: "phase1interface
      proposal: "aes256-sha1"
      auto_negotiate: "enable"
      dhgrp: "20"
      src_addr_type: "name"
      dst_addr_type: "name"
      src_name: "lan"
      dst_name: "remotelan"

**Comment by mbdraks** [comment]
Roles don't support the 'collections' keyword. Try using the full FQDN, e.g.:

`fortinet.fortios.fortios_vpn_ipsec_phase1_interface`

**Comment by kphillipsjr1101** [comment]
Sure enough that was the issue for that portion of the roles. Oddly enough, I didn't have any issues using some of the other modules in the collection without the FQDN.

Thank you for your help, I'll close this out since it's not a legitimate bug but a misunderstanding of keyword limitations.
