### ISSUE TITLE
Module Error: fortios_system_config_backup_restore (1.0.15)

### ISSUE THREAD

**Issue by 33Fraise33** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#50]
Hello,

I just tried the new 1.0.15 with the module which currently doesn't seem to be documented. I'm getting a module error during the play: 

Playbook: 
```
- hosts: fortigates
  collections:
   - fortinet.fortios
  connection: httpapi
  tasks:
  - name: backup global or a_specific_vdom settings
    fortios_system_config_backup_restore:
      config: "system config backup"
      backup: "yes"
      https: True
      ssl_verify: False
      scope: "vdom"
      filename: "/tmp/backup_test"
    register: config

  - debug:
      msg: "{{ config }}"
```

ansible version
```
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gianni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]

```

FortiOS Version: `6.2.3`

playbook output & error: 
```
The full traceback is:
Traceback (most recent call last):
  File "/home/gianni/.ansible/tmp/ansible-local-129237exkd2aw/ansible-tmp-1598526099.8403006-12983-87780068124564/AnsiballZ_fortios_system_config_backup_restore.py", line 102, in <module>
    _ansiballz_main()
  File "/home/gianni/.ansible/tmp/ansible-local-129237exkd2aw/ansible-tmp-1598526099.8403006-12983-87780068124564/AnsiballZ_fortios_system_config_backup_restore.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/gianni/.ansible/tmp/ansible-local-129237exkd2aw/ansible-tmp-1598526099.8403006-12983-87780068124564/AnsiballZ_fortios_system_config_backup_restore.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_config_backup_restore', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fortios_system_config_backup_restore_payload_3m0h85kx/ansible_fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py", line 344, in <module>
  File "/tmp/ansible_fortios_system_config_backup_restore_payload_3m0h85kx/ansible_fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py", line 329, in main
  File "/tmp/ansible_fortios_system_config_backup_restore_payload_3m0h85kx/ansible_fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py", line 211, in fortigate_backup
KeyError: 'results'
fatal: [fortigate01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/gianni/.ansible/tmp/ansible-local-129237exkd2aw/ansible-tmp-1598526099.8403006-12983-87780068124564/AnsiballZ_fortios_system_config_backup_restore.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/gianni/.ansible/tmp/ansible-local-129237exkd2aw/ansible-tmp-1598526099.8403006-12983-87780068124564/AnsiballZ_fortios_system_config_backup_restore.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/gianni/.ansible/tmp/ansible-local-129237exkd2aw/ansible-tmp-1598526099.8403006-12983-87780068124564/AnsiballZ_fortios_system_config_backup_restore.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_config_backup_restore', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_system_config_backup_restore_payload_3m0h85kx/ansible_fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py\", line 344, in <module>\n  File \"/tmp/ansible_fortios_system_config_backup_restore_payload_3m0h85kx/ansible_fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py\", line 329, in main\n  File \"/tmp/ansible_fortios_system_config_backup_restore_payload_3m0h85kx/ansible_fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py\", line 211, in fortigate_backup\nKeyError: 'results'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by JieX19** [comment]
@33Fraise33,

This module is the only one relies on fortiosapi, which will be deprecated in the next major release. Can you please check if fortiosapi is installed? **Using command: pip list**  to check.
**Using command: pip install fortiosapi** to install it if it's not existing.

Because it's using the legacy mode you cannot using any variables starting with ansible in your hosts file, like ansible_username etc.

Here's a workaround to solve the issue.
```
- hosts: localhost
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    host: "198.168.10.21"
    username: "admin"
    password: ""
  tasks:
  - name: backup global
    fortios_system_config_backup_restore:
      config: "system config backup"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom: "{{ vdom }}"
      backup: "yes"
      https: True
      ssl_verify: False
      scope: "global"
      filename: "./backup_global_test"
```

**Comment by 33Fraise33** [comment]
Hello,

Yes that module is installed: fortiosapi         1.0.3.
I did not know to remove the httpapi connection option.

When is the removal of this dependency planned?

**Comment by JieX19** [comment]
Hi,

Sorry to make you confused in. In the whole collection, all the modules are compatible with httpapi but this module (fortios_system_config_backup_restore), so we recommend to provide host, username and password in the playbook to trigger fortiosapi. 

If you put httpapi connection in the playbook I wrote above, it's fine, it will not make any errors but it's kinda useless. Fortiosapi will be called when host, username and password are provided. 
That's how the lelacy mode works.

For all the rest of modules, please use httpapi. 
Example as below:
```
- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
```
Because we still have a few user using the legacy mode, we will get you updated regarding the removal of this dependency.

**Comment by 33Fraise33** [comment]
Thanks, I got it working like you described, so I understand it currently doesn't use an inventory file.

my config if anyone needs this: 
```
- hosts: localhost
  collections:
   - fortinet.fortios
  tasks:
  - name: backup global or a_specific_vdom settings
    fortios_system_config_backup_restore:
      config: "system config backup"
      vdom: "root"
      host: "10.200.0.2"
      username: "admin"
      password: "password_here"
      backup: "yes"
      https: True
      ssl_verify: False
      scope: "vdom"
      filename: "/tmp/backup_test"
    register: test
  - debug:
      msg: "{{ test }}"
```

We will probably wait until the httpapi is implemented as well before using this module in production.

**Comment by JieX19** [comment]
Yes, it's a quick fix for the issue https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/38. We will have mortitor APIs included in the next major release and then this module will be deprecated. Thank you for your advice!

**Comment by sergioolovrap** [comment]
Hello,
there are any news about the issue?
Because I  have the same error
Regards

**Comment by JieX19** [comment]
@sergioolovrap,

This module is the only one relies on fortiosapi, which will be deprecated in the next major release. Can you please check if fortiosapi is installed? Using command: pip list to check.
Using command: pip install fortiosapi to install it if it's not existing.

Because it's using the legacy mode you cannot using any variables starting with ansible in your hosts file, like ansible_username etc. 

In the whole collection, all the modules are compatible with httpapi but this module (fortios_system_config_backup_restore), so we recommend to provide host, username and password in the playbook to trigger fortiosapi.

If you put httpapi connection in the playbook I wrote above, it's fine, it will not make any errors but it's kinda useless. Fortiosapi will be called when host, username and password are provided.
That's how the lelacy mode works.

Here's the correct playbook to solve the issue.

```
- hosts: localhost
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    host: "198.168.10.21"
    username: "admin"
    password: ""
  tasks:
  - name: backup global
    fortios_system_config_backup_restore:
      config: "system config backup"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom: "{{ vdom }}"
      backup: "yes"
      https: True
      ssl_verify: False
      scope: "global"
      filename: "./backup_global_test"
```

**Comment by JieX19** [comment]
@sergioolovrap,

Can you please provide us more details about the error if the above solution does not work for you?

**Comment by sergioolovrap** [comment]
> @sergioolovrap,
> 
> Can you please provide us more details about the error if the above solution does not work for you?
Hello,
i copied your playbook but now seem don't recognize  "fortios_system_config_backup_restore":

(venv) [root@localhost playbook]# ansible-playbook issue_fortios.yml 
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
ERROR! couldn't resolve module/action 'fortios_system_config_backup_restore'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/etc/ansible/playbook/issue_fortios.yml': line 10, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - name: backup global
    ^ here

**Comment by JieX19** [comment]
@sergioolovrap,

The error "An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named fortiosapi" means there's no fortiosapi installed in your device.

Using command **pip install fortiosapi to install it**. This is the legacy mode we were using before and it's the only module relying on fortiosapi and it will be deprecated in the near future.

Also, please delete all the parameters starting with **ansible_**, the key words only get working when using httpapi. Please follow the example playbook I provided above.

**Comment by chillancezen** [comment]
solution in https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/50#issuecomment-710682178.

it's recommended to use new modules with collection later than `2.0.0`: https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-backup-and-restore-fos
