### ISSUE TITLE
SD-WAN changes in 6.4.1

### ISSUE THREAD

**Issue by trevorludgate** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#59]
In 6.4.1, Fortinet changed how SD-WAN is configured. There are now named SD-WAN zones instead of using a global SD-WAN 'group'. 
Documentation:
https://docs.fortinet.com/document/fortigate/6.4.1/administration-guide/218559/configuring-the-sd-wan-interface
Release notes:
https://docs.fortinet.com/document/fortigate/6.4.1/fortios-release-notes/251225/sd-wan-upgrade-changes

As expected, this breaks fortios_system_virtual_wan_link since there is no field for the zone name.

Please let me know what I can do to help troubleshoot this - thanks!

Using module version 1.0.11

Configuration of the task:

```
  - name: Configure SDWAN.
    fortios_system_virtual_wan_link:
      system_virtual_wan_link:
        members:
         -
            seq-num: "1"
            interface: "wan1"
            status: "enable"
         -
            seq-num: "2"
            interface: "wan2"
            status: "enable" 
        status: "enable"
```

Result (-vvv):
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<10.0.30.172> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.0.30.172> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-8145u6w1fzac `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-8145u6w1fzac/ansible-tmp-1601940262.3799806-8309-238715919498361 `" && echo ansible-tmp-1601940262.3799806-8309-238715919498361="` echo /root/.ansible/tmp/ansible-local-8145u6w1fzac/ansible-tmp-1601940262.3799806-8309-238715919498361 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_virtual_wan_link.py
<10.0.30.172> PUT /root/.ansible/tmp/ansible-local-8145u6w1fzac/tmpc_pquyt2 TO /root/.ansible/tmp/ansible-local-8145u6w1fzac/ansible-tmp-1601940262.3799806-8309-238715919498361/AnsiballZ_fortios_system_virtual_wan_link.py
<10.0.30.172> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-8145u6w1fzac/ansible-tmp-1601940262.3799806-8309-238715919498361/ /root/.ansible/tmp/ansible-local-8145u6w1fzac/ansible-tmp-1601940262.3799806-8309-238715919498361/AnsiballZ_fortios_system_virtual_wan_link.py && sleep 0'
<10.0.30.172> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-8145u6w1fzac/ansible-tmp-1601940262.3799806-8309-238715919498361/AnsiballZ_fortios_system_virtual_wan_link.py && sleep 0'
<10.0.30.172> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-8145u6w1fzac/ansible-tmp-1601940262.3799806-8309-238715919498361/ > /dev/null 2>&1 && sleep 0'
fatal: [test-fgt]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "host": null,
            "https": true,
            "password": "",
            "ssl_verify": true,
            "system_virtual_wan_link": {
                "fail_alert_interfaces": null,
                "fail_detect": null,
                "health_check": null,
                "load_balance_mode": null,
                "members": [
                    {
                        "interface": "wan1",
                        "seq-num": "1",
                        "status": "enable"
                    },
                    {
                        "interface": "wan2",
                        "seq-num": "2",
                        "status": "enable"
                    }
                ],
                "neighbor": null,
                "neighbor_hold_boot_time": null,
                "neighbor_hold_down": null,
                "neighbor_hold_down_time": null,
                "service": null,
                "status": "enable"
            },
            "username": null,
            "vdom": "root"
        }
    },
    "meta": {
        "build": 1723,
        "http_method": "PUT",
        "http_status": 400,
        "name": "virtual-wan-link",
        "path": "system",
        "serial": "[REDACTED]",
        "status": "error",
        "vdom": "root",
        "version": "v6.4.2"
    },
    "msg": "Error in repo"
}

**Comment by trevorludgate** [comment]
This section of the documentation is more relevant:
https://docs.fortinet.com/document/fortigate/6.4.1/administration-guide/942095/sd-wan-zones

**Comment by chillancezen** [comment]
eta:11.11.2020

**Comment by chillancezen** [comment]
hi @trevorludgate ,

please see the hot build for new SDWAN feature: https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/releases/tag/Hotbuild%2F6.4.1%2Fsdwan

we built this as temporary workaround, in the future we may have official support for this. 

thanks,
Link

**Comment by chillancezen** [comment]
not an issue after `2.0.0` is released.
