### ISSUE TITLE
How to check if user is present in a user group on Fortigate ?

### ISSUE THREAD

**Issue by greenspartan** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#63]
Hi !

I need to create a playbook that will check if a particular user is member of a user group.
I didn't find any modules in Fortios ansible collection that can achieve this (like a search or find module).
Is the only option is to retrieve config using fortios_system_config_backup_restore module, then search into plain text config file ?
Or is there a smartest way to achieve it using another modules ?

By the way thanks a lot to Fortinet dev team for all amazing modules that have already been created ;) !!!

Have a good day !

Adrien

**Comment by chillancezen** [comment]
Thank you so much for using fortios collection @greenspartan .

we are sorry that we don't have sufficient support for `fortios_facts` which is going to query objects.  the recommended way is to use `fortios_generic` module. https://github.com/fortinet/ansible-fortios-generic

we will support full objects for `fmgr_facts` in about few weeks.

please let us know if you have any issues. 
thanks,
Link

**Comment by greenspartan** [comment]
Hi Link,

Thanks a lot for your feedback @chillancezen  👍  ! I will check fortios_generic module and keep an eye on fortios_facts support progress during upcoming weeks ;-)

Have a good day !

Best Regards,

Adrien

**Comment by chillancezen** [comment]
> Hi Link,
> 
> Thanks a lot for your feedback @chillancezen 👍 ! I will check fortios_generic module and keep an eye on fortios_facts support progress during upcoming weeks ;-)
> 
> Have a good day !
> 
> Best Regards,
> 
> Adrien

thanks for your understanding. 
we will keep it open until fix/enhancement is ready.

thanks,
Link

**Comment by chillancezen** [comment]
hi @greenspartan ,
we have support to retrieve configuration via `GET` method.  please install latest galaxy FortiOS collection.
```
$ansible-galaxy collection install -f fortinet.fortios
```
https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_configuration_fact.html


the selector is `user_group `.

mark this issue `closed`.

thanks,
Link
