### ISSUE TITLE
Idempotency for most of fortios firewall modules

### ISSUE THREAD

**Issue by defus** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#66]
Hello,

I remark that when i run multiple time the same Ansible script using fortios modules Ansible says that there are changes event if i dont modify my inventories (like **fortios_firewall_schedule_recurring, fortios_firewall_address, fortios_firewall_addrgrp, fortios_firewall_vip, fortios_firewall_service_custom, fortios_firewall_policy**)

How can i do the have idempotency on Ansible fortios scripts.

Thanks

**Comment by hunter86bg** [comment]
I can confirm that 'fortios_system_interface' also is not idempotent.
Debug is enabled via:
```
hostname1 $ diagnose debug enable
hostname1 $ diagnose debug cli 8
```
Output generated from debug when rerunning 'fortios_system_interface':
```
hostname1 $ 0: config system interface
0: edit "loopback"
0: end
0: config system interface
0: edit "loopback"
0: config ipv6
0: end
0: end
```

**Comment by chillancezen** [comment]
> Hello,
> 
> I remark that when i run multiple time the same Ansible script using fortios modules Ansible says that there are changes event if i dont modify my inventories (like **fortios_firewall_schedule_recurring, fortios_firewall_address, fortios_firewall_addrgrp, fortios_firewall_vip, fortios_firewall_service_custom, fortios_firewall_policy**)
> 
> How can i do the have idempotency on Ansible fortios scripts.
> 
> Thanks

thanks @defus  for the issue, 

Idempotency is running one playbook multiple times and same result returned.  if so, most of the modules has that behavior.  especially with FortiOS later than 6.2.3, an option `revision_changed` was introduced to describe precisely whether an API request triggers any changes.
```
    "meta": {
        "build": 1579,
        "http_method": "PUT",
        "http_status": 200,
        "mkey": "FW/ADDRESS?! with escape letters",
        "name": "address",
        "path": "firewall",
        "revision": "929b4ec86aa74ef610d270153b7621d7",
        "revision_changed": false,
        "serial": "FGVMEVFQP-EBQU92",
        "status": "success",
        "vdom": "root",
        "version": "v6.4.0"
    },
```
so could you help share your playbook and expected state with us?

thanks,
Link.

**Comment by chillancezen** [comment]
> I can confirm that 'fortios_system_interface' also is not idempotent.
> Debug is enabled via:
> 
> ```
> hostname1 $ diagnose debug enable
> hostname1 $ diagnose debug cli 8
> ```
> 
> Output generated from debug when rerunning 'fortios_system_interface':
> 
> ```
> hostname1 $ 0: config system interface
> 0: edit "loopback"
> 0: end
> 0: config system interface
> 0: edit "loopback"
> 0: config ipv6
> 0: end
> 0: end
> ```
> 
> It's really strange why it edits ipv6 when I have never defined one.

thank you @hunter86bg for your comment,
it the API server which explains API request and converts to CLI-like lines. 

the API server is doing one stateful update so that it counts even empty ipv6 entries.
please correct me if my comment doesn't explain your confusion.


thanks,
Link

**Comment by chillancezen** [comment]
> I remark that when i run multiple time the same Ansible script using fortios modules Ansible says that there are changes event if i dont modify my inventories

Hi @defus Landry,  I guess that you are running playbooks on top of Fortigate 6.0. in case, you will always receive `changed` event.

if you are running with Fortigate 6.2(later 6.2.3) or 6.4 series, things get a little different, no modification will reflect at ansible side if your playbooks are not modified.
