### ISSUE TITLE
fortios_router_bgp unable to pass remote as

### ISSUE THREAD

**Issue by toy4two** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#7]
I am unable to create a BGP neighbor.   I am unable to pass **remote_as** attribute using the fortios_router_bgp.  remote_as is not defined as required, but it should be in the docs. fortios does not accept neighbor statements without a remote_as.

      - name: Configure BGP Neighbor.
        fortios_router_bgp:
          host: "{{ inventory_hostname }}"
          https: "yes"
          ssl_verify: "no"
          vdom: "{{ vdom_name }}"
          username: "{{ username }}"
          password: "{{ password }}"
          router_bgp:      
            neighbor:
             -
                ip: "192.168.1.1"
                remote_as: "1111"

TASK [Configure BGP Neighbor.] *****************************************
fatal: [device]: FAILED! => {"changed": false, "meta": {"build": 1066, "http_method": "POST", "http_status": 405, "name": "bgp", "path": "router", "serial": "FGxxxxxxx", "status": "error", "vdom": "test", "version": "v6.2.3"}, "msg": "Error in repo"}

DEBUG on Fortigate

0: config vdom
2305 1 cmd =
end
0: edit test
0: config router bgp
0: config neighbor
0: edit "192.168.1.1"
1: end
2306 1 cmd =
config vdom
edit test
config router bgp
config neighbor
edit 192.168.1.1
abort
abort

**Comment by toy4two** [comment]
I have found the solution.  

**remote-as** is the correct attribute to pass not **remote_as** as stated in the documentation.

**Comment by chillancezen** [comment]
This has been fixed in next release.
