### ISSUE TITLE
Raw FortiOS CLI Function collection

### ISSUE THREAD

**Issue by chillancezen** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#70]
issue list:
- #53 move
- #14 unset
- https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/72 

possible solution

- `fortiosconfig` module
- Ansible `shell`, `script` and `command` module
- non-Ansible raw shell&script commands

**Comment by chillancezen** [comment]
mantic #0659238

**Comment by JonTheNiceGuy** [comment]
Likewise, I need to be able to perform actions like `get system ha status`, so either repurposing [the fortiosconfig](https://github.com/fortinet-solutions-cse/40ansible/blob/master/library/fortiosconfig.py) code to use httpapi or having a `fortios_system_ha_facts` module for any "get" commands would also be useful. Happy to help in whatever way I can!

**Comment by chillancezen** [comment]
> Likewise, I need to be able to perform actions like `get system ha status`, so either repurposing [the fortiosconfig](https://github.com/fortinet-solutions-cse/40ansible/blob/master/library/fortiosconfig.py) code to use httpapi or having a `fortios_system_ha_facts` module for any "get" commands would also be useful. Happy to help in whatever way I can!

thanks @JonTheNiceGuy ,

we will have this supported in next release very soon, please stay tuned!

**Comment by JonTheNiceGuy** [comment]
Just for your awareness, in a previous body of code, using the legacy connection, [I've made extensive use of the `fortiosconfig` module](https://github.com/E-and-CS/fortigate_policy/search?q=fortiosconfig%3A) (link is to search in a repo, and is provided so you can get some context on what I've used it for) and was working with @mamunozgonzalez (who can probably vouch for me and what I've done before with Ansible+FortiGate). If you're planning to port this over, I'd be super happy 😁

**Comment by chillancezen** [comment]
> Just for your awareness, in a previous body of code, using the legacy connection, [I've made extensive use of the `fortiosconfig` module](https://github.com/E-and-CS/fortigate_policy/search?q=fortiosconfig%3A) (link is to search in a repo, and is provided so you can get some context on what I've used it for) and was working with @mamunozgonzalez (who can probably vouch for me and what I've done before with Ansible+FortiGate). If you're planning to port this over, I'd be super happy 😁

thank you so much for your work, please give me some time to get familiar with the context&mechanism and find the point to integrate with our generator(our modules now are all generated by a generator, even fact modules are going to be generated for next releases.)

thanks again, I will keep you updated.
Link

**Comment by chillancezen** [comment]
recommended solution: http://192.168.190.159/_build/html/faq.html#how-to-work-with-raw-fotios-cli
