### ISSUE TITLE
Module Error: fortios_system_config_backup_restore 

### ISSUE THREAD

**Issue by toggit** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#75]
Helllo Guys,

I use the module fortios_system_config_backup_restore for backup all my fortigates in the datacenter.
but some of them return this error:

An exception occurred during task execution. To see the full traceback, use -vvv. 
The error was: fatal: [10.10.30.254]: FAILED! => {"changed": false, "module_stderr": "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.10.30.254'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.10.30.254'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.10.30.254'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 426, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 421, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib64/python3.6/http/client.py\", line 1346, in getresponse\n    response.begin()\n  File \"/usr/lib64/python3.6/http/client.py\", line 307, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib64/python3.6/http/client.py\", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib64/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/lib64/python3.6/ssl.py\", line 971, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/lib64/python3.6/ssl.py\", line 833, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/lib64/python3.6/ssl.py\", line 590, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n    timeout=timeout\n  File \"/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 727, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py\", line 403, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py\", line 735, in reraise\n    raise value\n  File \"/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 677, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 428, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 336, in _raise_timeout\n    self, url, \"Read timed out. (read timeout=%s)\" % timeout_value\nurllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='10.10.30.254', port=983): Read timed out. (read timeout=12)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1606268478.3414114-1747793-71818949121011/AnsiballZ_fortios_system_config_backup_restore.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1606268478.3414114-1747793-71818949121011/AnsiballZ_fortios_system_config_backup_restore.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1606268478.3414114-1747793-71818949121011/AnsiballZ_fortios_system_config_backup_restore.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_config_backup_restore', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_system_config_backup_restore_payload_jvjdlc3k/ansible_fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py\", line 344, in <module>\n  File \"/tmp/ansible_fortios_system_config_backup_restore_payload_jvjdlc3k/ansible_fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py\", line 329, in main\n  File \"/tmp/ansible_fortios_system_config_backup_restore_payload_jvjdlc3k/ansible_fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py\", line 201, in fortigate_backup\n  File \"/usr/local/lib/python3.6/site-packages/fortiosapi/fortiosapi.py\", line 447, in monitor\n    res = self._session.get(url, params=parameters, timeout=self.timeout)\n  File \"/usr/local/lib/python3.6/site-packages/requests/sessions.py\", line 543, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/requests/sessions.py\", line 530, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/requests/sessions.py\", line 643, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/requests/adapters.py\", line 529, in send\n    raise ReadTimeout(e, request=request)\nrequests.exceptions.ReadTimeout: HTTPSConnectionPool(host='10.10.30.254', port=983): Read timed out. (read timeout=12)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

I think this error is about timeout but why only this specific fortigate fails?
and how do i change the timeout?  "Read timed out. (read timeout=12)"
i tried to set the ansible env variable timeout setting but i don't think this module use this variable.

this is my task:
```
  - name: backup global or a_specific_vdom settings
    connection: httpapi
    fortios_system_config_backup_restore:
      config: "system config backup"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom: "{{ vdom }}"
      backup: "yes"
      https: True
      ssl_verify: False
      scope: "global"
      filename: "/tmp/backup_test{{host}}"
    tags:
    - backup
```

tnx,

**Comment by chillancezen** [comment]
hi @toggit,

thanks for using FortiOS ansible, 
could you please help provide your full playbook and inventory with credentials masked?

a good playbook for the module is https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/50#issuecomment-705109972

thanks,
Link

**Comment by toggit** [comment]
Hi Chillancezen
here is my playbook and inventory:

playbook.yml:

```
- hosts: all
  gather_facts: no
  connection: local
  collections:
    - fortinet.fortios
  vars:
    host: "{{ ansible_host }}:{{ ansible_port }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    vdom: "root"
    ssl_verify: "False"

  tasks:
  - name: print the vars    
    debug:
      msg: 
      - "{{ansible_host}} , {{test}}"
      - "from inventory file: user = {{ ansible_user }}, password = {{ ansible_password }}, port = {{ ansible_port }}"
      - "from local vars: user = {{ username }}, password = {{ password }}, port = {{ host }}"
      - "timeout = {{ ansible_persistent_connect_timeout }}"
    tags:
    - backup
    - var
    - facts
      
  - name: gather gather all physical and vlan interfaces status facts
    fortios_facts:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      gather_subset:
        - fact: 'system_status_select'
        - fact: 'system_interface_select'
          filters:
            - include_vlan: true
    register: result
    tags:
    - facts

  - name: print the facts    
    debug:
      msg: "{{ ansible_facts.network_resources.system_status_select }}"
    tags:
    - facts

  - name: backup global or a_specific_vdom settings
    connection: httpapi
    fortios_system_config_backup_restore:
      config: "system config backup"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom: "{{ vdom }}"
      backup: "yes"
      https: True
      ssl_verify: False
      scope: "global"
      filename: "/tmp/backup_test{{host}}"
    tags:
    - backup
```


inventory file:

```
forti:
  hosts:
    forti_40_15:
      ansible_host: 10.10.40.15
    forti_30_15:
      ansible_host: 10.10.30.15 
    forti_30_16:
      ansible_host: 10.10.30.16
    forti_30_13:
      ansible_host: 10.10.30.13
      ansible_port: 981
    forti_30_254:
      ansible_host: 10.10.30.254
      ansible_port: 983
  vars:
    test: test_var123
    ansible_user: admin
    ansible_password:  mypassword
    ansible_connection: local
    ansible_port: 982
```

**Comment by chillancezen** [comment]
hi @toggit , 

we have released new modules to support backup and restore in FOS galaxy collection later than `2.0.0`. 
```
ansible-galaxy collection install -f fortinet.fortios
```

could you please see https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-backup-and-restore-fos ?

let us know whether it solves your issue.

thanks.

**Comment by chillancezen** [comment]
mark it `closed`, please feel free to reopen if issue persists.

**Comment by ramepetla** [comment]
Using Version 2.2.2, same issue
ERROR! couldn't resolve module/action 'fortinet.fortios.fortios_system_config_backup_restore'. This often indicates a misspelling, missing collection, or incorrect module path.
