### ISSUE TITLE
Introduce a way to audit config and deploy intended_config for fortios

### ISSUE THREAD

**Issue by ryanmerolle** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#80]
Currently with other network_os modules, you can select a golden config ("intended_config") to either replace the full config or if you set check_mode, you can use the intended_config to audit diffs between running config and intended_config.  It would be useful for this to be introduced for fortios.

Example: https://docs.ansible.com/ansible/latest/collections/arista/eos/eos_config_module.html

**Comment by ryanmerolle** [comment]
A very common CI/CD pipeline is to generate a full config, test against it using linters, batfish, etc, test deploy using config_replace and check_mode in Ansible.  I am currently doing this for my other vendor gear, but not fortios.

With firewall policies, adhoc/workflow based deployments make perfect sense.  With small branch offices with VPNs, WAN circuits, generic (non-changing) firewall rules, that provide user access switchports, deploying and auditing full configs would be very useful.

**Comment by JieX19** [comment]
Hi @ryanmerolle,

Good question! Check_mode feature is available for fortios_system_interface in our latest version of fortios but has not been expanded to all the modules. We are gonna introduce this feature to all modules.

We will take intended_config feature into consideration.

**Comment by carlos-segundo** [comment]
Hi,

Check mode has been introduced to the latest version of fortios? Do you mean that this functionality has to come in a OS update?

Will this support be in the 6.4 or only in the 6.6 release train?

**Comment by JieX19** [comment]
@carlos-segundo,

Oh...it's my bad. I mean check_mode feature is available for our latest ansible galaxy collection and not about OS update. You may install the latest version to use it. Please use the following command to update the ansible galaxy collection on your device.

version 6.0.0            ansible-galaxy collection install fortinet.fortios:1.1.8 -f

version 6.2.0            ansible-galaxy collection install fortinet.fortios:1.1.6 -f

version 6.4.0            ansible-galaxy collection install fortinet.fortios:1.1.7 -f

**Comment by ryanmerolle** [comment]
This is good progress.  Combined with some of the work in #79 , a golden config audit feels like it is around the corner.

**Comment by JieX19** [comment]
Hi @ryanmerolle,

Can I clarify a question with you? Did you mean that you wanna check_mode on all the configurations at once? For example, you get the complete configurations of the device and do check_mode on all of the configs. Or just do check_mode on different modules separately.

Thanks,
Jie

**Comment by JieX19** [comment]
Replied in #79
