### ISSUE TITLE
SNMP trap events missing in system_snmp_community module

### ISSUE THREAD

**Issue by jguirlinger** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#89]
When using system_snmp_community module, one parameter is "events" and accept a list of snmp trap event.
The module verify each element against a predefined list but this list is missing 4 of them :
temperature-high
voltage-alert
power-supply-failure
fan-failure

Seems to be all hardware related events

**Comment by chillancezen** [comment]
hi @jguirlinger ,

next release will include all them: https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/gen/fortios_system_snmp_community.html

thanks for reaching out.

**Comment by chillancezen** [comment]
hi @jguirlinger ,

FOS Galaxy collection release later than 2.0.0 includes the fix.

https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_system_snmp_community.html

mark it `closed`, feel free to reopen if further assistance is needed.
thanks.
