### ISSUE TITLE
PermissionError due to httpapi plugin log 

### ISSUE THREAD

**Issue by targuan** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#91]
Hello,

Currently, the httpapi plugin is writting the logs to `/tmp/fortios.ansible.log`.
The file is created by the first user using the modules. If the host is shared by several user, the other may get a PermissionError if they don't have enough right on the file.
Could it be possible to use a per user log file in order to avoir such error ?

**Comment by chillancezen** [comment]
Good point. 
 thank you @targuan

**Comment by chillancezen** [comment]
mark `closed`, feature issued in FortiOS galaxy 2.0.0 very soon.
