### ISSUE TITLE
Misspelling, missing collection, or incorrect module path for fortios_system_config_backup_restore

### ISSUE THREAD

**Issue by gitnetofr** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#95]
Hi, 

I'm trying to retrieve the configuration from a Fortigate using the module `fortios_system_config_backup_restore` and basing on your [playbook example](https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_system_config_backup_restore_module.html#examples). 

I have `ansible 2.10.6`. 

When I use the collection `fortinet.fortios:1.1.8`, I got the following error: `missing 1 required positional argument: 'mod'`

```
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-local-8668osvgufxk/ansible-tmp-1615481963.0092971-8768-3877705280026/AnsiballZ_fortios_system_config_backup_restore.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-local-8668osvgufxk/ansible-tmp-1615481963.0092971-8768-3877705280026/AnsiballZ_fortios_system_config_backup_restore.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-local-8668osvgufxk/ansible-tmp-1615481963.0092971-8768-3877705280026/AnsiballZ_fortios_system_config_backup_restore.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_config_backup_restore', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fortinet.fortios.fortios_system_config_backup_restore_payload_mplamrs7/ansible_fortinet.fortios.fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py", line 472, in <module>
  File "/tmp/ansible_fortinet.fortios.fortios_system_config_backup_restore_payload_mplamrs7/ansible_fortinet.fortios.fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py", line 436, in main
TypeError: __init__() missing 1 required positional argument: 'mod'
fatal: [fortigate-01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansible/.ansible/tmp/ansible-local-8668osvgufxk/ansible-tmp-1615481963.0092971-8768-3877705280026/AnsiballZ_fortios_system_config_backup_restore.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ansible/.ansible/tmp/ansible-local-8668osvgufxk/ansible-tmp-1615481963.0092971-8768-3877705280026/AnsiballZ_fortios_system_config_backup_restore.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ansible/.ansible/tmp/ansible-local-8668osvgufxk/ansible-tmp-1615481963.0092971-8768-3877705280026/AnsiballZ_fortios_system_config_backup_restore.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_config_backup_restore', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortinet.fortios.fortios_system_config_backup_restore_payload_mplamrs7/ansible_fortinet.fortios.fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py\", line 472, in <module>\n  File \"/tmp/ansible_fortinet.fortios.fortios_system_config_backup_restore_payload_mplamrs7/ansible_fortinet.fortios.fortios_system_config_backup_restore_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_config_backup_restore.py\", line 436, in main\nTypeError: __init__() missing 1 required positional argument: 'mod'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

Using the recent pre release `fortinet.fortios:2.0.0` , I got:

```
ERROR! couldn't resolve module/action 'fortinet.fortios.fortios_system_config_backup_restore'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ansible/backup.yml': line 46, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: backup global or a_specific_vdom settings
    
  ```
  
  No module found in `~/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/ `
  
  Any idea? 
  
  Thanks.

**Comment by chillancezen** [comment]
hi @gitnetofr, 

could you please install 1.1.9 by ?
```
$ansible-galaxy collection install -f fortinet.fortios:1.1.9
```

this was fixed in 1.1.9. 

in collection fortios 2.0.0, we deprecate several modules, `fortios_system_config_backup_restore` is one of them. (https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/release.html#release-galaxy-2-0-0)
 2.0.0 is a breaking collection, we are considering build some guide page to show how to migrate deprecated modules.

thanks,
Link

**Comment by gitnetofr** [comment]
Hi @chillancezen, 

With 1.1.9 it works beautifully. Thanks. 😄 

In the release notes of 2.0.0 you suggest to use `fortios_monitor_fact` with `system_config_backup`, since I didn't see the example using ansible-doc, can you confirm if this usage is correct with the collection 2.0.0, please?

```
    - name: backup global 
      fortios_monitor_fact:
        selector: system_config_backup
        access_token: "{{ fortios_access_token }}"
        vdom: "{{ vdom | default('root') }}"
```

Thank you very much.

**Comment by chillancezen** [comment]
we are going to write some examples very soon before 2.0.0 is released. and I willupdate you

thanks


Sent from my iPhone

On Mar 12, 2021, at 8:50 PM, gitnetofr ***@***.***> wrote:

﻿

Hi @chillancezen<https://github.com/chillancezen>,

With 1.1.9 it works beautifully. Thanks. 😄

In the release notes of 2.0.0 you suggest to use fortios_monitor_fact with system_config_backup, since I didn't see the example using ansible-doc, can you confirm if this usage is correct with the collection 2.0.0, please?

    - name: backup global
      fortios_monitor_fact:
        selector: system_config_backup
        access_token: "{{ fortios_access_token }}"
        vdom: "{{ vdom | default('root') }}"


Thank you very much.

**Comment by gitnetofr** [comment]
Hi @chillancezen, 

Thanks. 
We are looking forward to this new release. 
Would it be possible to give me an approximate date for the 2.0.0 stable release?

Thank you.

**Comment by chillancezen** [comment]
> Hi @chillancezen,
> 
> Thanks.
> We are looking forward to this new release.
> Would it be possible to give me an approximate date for the 2.0.0 stable release?
> 
> Thank you.

plan to release at the end of March.

thanks,

**Comment by chillancezen** [comment]
@gitnetofr  https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/faq.html#how-to-backup-and-restore-fos please see example here.

**Comment by gitnetofr** [comment]
> > Hi @chillancezen,
> > Thanks.
> > We are looking forward to this new release.
> > Would it be possible to give me an approximate date for the 2.0.0 stable release?
> > Thank you.
> 
> plan to release at the end of March.
> 
> thanks,

Hi, do you already have a stable release since `pre-2.0.0` for unified FOS versions? 

Thank you!

**Comment by chillancezen** [comment]
hi @gitnetofr ,

yes, please install latest collection:
```
ansible-galaxy collection install fortinet.fortios -f
```

doc: https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-backup-and-restore-fos

mark it `closed`.  please feel free to reopen or create another issue if there is anything we could do to help. 

thanks,
Link

**Comment by gitnetofr** [comment]
Thank you!!! 😉

**Comment by crougher** [comment]
I have 'fortinet.fortios:2.0.2' and still can see this issue.
Any idea why?

``
# /home/czarny/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.1.0  
ansible.utils     2.2.0  
fortinet.fortios  2.0.2  

czarny@crougher:~/code/Ansible/1ansible$ ls -l /home/czarny/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor*
-rw-r--r-- 1 czarny czarny 74641 Jun 17 14:50 /home/czarny/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py
-rw-r--r-- 1 czarny czarny 14066 Jun 17 14:50 /home/czarny/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitoring_np6_ipsec_engine.py
-rw-r--r-- 1 czarny czarny 65325 Jun 17 14:50 /home/czarny/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor.py


Error is below:
ERROR! couldn't resolve module/action 'fortios_monitor_fact'. This often indicates a misspelling, missing collection, or incorrect module path.

**Comment by Outsourcing24** [comment]
@crougher, I have the exact same problem as yours. I can't figure out why it's not working. Everything seems to be ok.
I'm on a new OS (Ubuntu 20), and it's giving me the same problem. Ansible can't find the fortios_monitor_fact module.

Did you resolve this problem ?
