### ISSUE TITLE
Var "APPEND" on fortios_firewall_addrgrp

### ISSUE THREAD

**Issue by Eddie0818** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#96]
On CLI while adding a Firewall Address on a Firewall Group you can use the command

` FG_7060E [FIM01] (FG-VPN-IPs) # append member FA_Example_10.10.10.0/24 `

In which you can add a new firewall address without overriding the old firewall address

Is it possible to do this kind of setup with a playbook?

**Comment by JieX19** [comment]
@Eddie0818,

Here's a workaround to add members on a Firewall Group. https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/36

Please let us know if you have any other questions.

**Comment by chillancezen** [comment]
hi @Eddie0818 Eddie, 
we also have a template to execute FortiOS cli commands from Ansible.
please see examples in https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-work-with-raw-fotios-cli

mark it `closed`, please feel free to reopen.
