### ISSUE TITLE
vpn_ipsec_phase1_interface and vpn_ipsec_phase2_interface Proposal issue 

### ISSUE THREAD

**Issue by jojoflyhigh** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#97]
When configuring vpn ipsec Phase1 or Phase2  interface according to available proposal, only a few are implemented into ansible fortios module:

 "msg": "value of proposal must be one of: des-md5, des-sha1, des-sha256, des-sha384, des-sha512, got: aes256-sha256 found in vpn_ipsec_phase1_interface",
  "invocation": {
    "module_args": {
      "host": "X.X.X.X",
      "username": "admin",
      "password": "my_password",
      "ssl_verify": false,
      "vdom": "MY_VDOM",
      "state": "present",
      "vpn_ipsec_phase1_interface": {
        "name": "MY_VDOM",
        "type": "dynamic",
        "interface": "Intf",
        "ike_version": "2",
        "local_gw": "55.55.55.1",
        "peertype": "any",
        "net_device": "disable",
        "proposal": "aes256-sha256",
        "localid": "55.55.55.1",
        "dpd": "on-idle",
        "nattraversal": "disable",
        "psksecret": "123456789",
        "dpd_retryinterval": "60"
      },
      "https": true
    }
  },
  "_ansible_no_log": false,
  "changed": false
}

Proposal implemented into foritnet are :
des-md5                       des-md5
des-sha1                      des-sha1
des-sha256                    des-sha256
des-sha384                    des-sha384
des-sha512                    des-sha512
3des-md5                      3des-md5
3des-sha1                     3des-sha1
3des-sha256                   3des-sha256
3des-sha384                   3des-sha384
3des-sha512                   3des-sha512
aes128-md5                    aes128-md5
aes128-sha1                   aes128-sha1
aes128-sha256                 aes128-sha256
aes128-sha384                 aes128-sha384
aes128-sha512                 aes128-sha512
aes128gcm-prfsha1             aes128gcm-prfsha1
aes128gcm-prfsha256           aes128gcm-prfsha256
aes128gcm-prfsha384           aes128gcm-prfsha384
aes128gcm-prfsha512           aes128gcm-prfsha512
aes192-md5                    aes192-md5
aes192-sha1                   aes192-sha1
aes192-sha256                 aes192-sha256
aes192-sha384                 aes192-sha384
aes192-sha512                 aes192-sha512
aes256-md5                    aes256-md5
aes256-sha1                   aes256-sha1
aes256-sha256                 aes256-sha256
aes256-sha384                 aes256-sha384
aes256-sha512                 aes256-sha512
aes256gcm-prfsha1             aes256gcm-prfsha1
aes256gcm-prfsha256           aes256gcm-prfsha256
aes256gcm-prfsha384           aes256gcm-prfsha384
aes256gcm-prfsha512           aes256gcm-prfsha512
chacha20poly1305-prfsha1      chacha20poly1305-prfsha1
chacha20poly1305-prfsha256    chacha20poly1305-prfsha256
chacha20poly1305-prfsha384    chacha20poly1305-prfsha384
chacha20poly1305-prfsha512    chacha20poly1305-prfsha512
aria128-md5                   aria128-md5
aria128-sha1                  aria128-sha1
aria128-sha256                aria128-sha256
aria128-sha384                aria128-sha384
aria128-sha512                aria128-sha512
aria192-md5                   aria192-md5
aria192-sha1                  aria192-sha1
aria192-sha256                aria192-sha256
aria192-sha384                aria192-sha384
aria192-sha512                aria192-sha512
aria256-md5                   aria256-md5
aria256-sha1                  aria256-sha1
aria256-sha256                aria256-sha256
aria256-sha384                aria256-sha384
aria256-sha512                aria256-sha512
seed-md5                      seed-md5
seed-sha1                     seed-sha1
seed-sha256                   seed-sha256
seed-sha384                   seed-sha384
seed-sha512                   seed-sha512

**Comment by chillancezen** [comment]
the release 2.0.0 will support all those. 
https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/gen/fortios_vpn_ipsec_phase1_interface.html

Will update you when 2.0.0 is released at the end of March.

**Comment by jojoflyhigh** [comment]
Thanks for this update.

**Comment by JieX19** [comment]
Hi @jojoflyhigh,

Please try our new release 2.0.0 and let us know if you have any questions.

Using command **ansible-galaxy collection install fortinet.fortios:2.0.0**

**Comment by jojoflyhigh** [comment]
Hi @JieX19,
Works fine for me in 2.0.0 and 2.0.1 for this topic
Thanks for this update.
